// GENERATED by `harn dump-protocol-artifacts` - do not edit by hand.
// Source: Harn adapter schemas and Harn-owned wire registries.

export const HARN_PROTOCOL_ARTIFACT_VERSION = "0.10.126-dev"

export const HARN_TOOL_PERMISSION_DECISION_SCHEMA = "harn.tool_permission_decision.v1" as const
export const HARN_TOOL_PERMISSION_ACTIVITY_SCHEMA = "harn.tool_permission_activity.v1" as const

export const HARN_EXTERNAL_ACTION_ACTIVITY_SCHEMA = "harn.external_action_activity.v1" as const
export const HARN_EXTERNAL_ACTION_RECEIPT_SCHEMA = "harn.external_action_receipt.v1" as const

export const MCP_PROTOCOL_VERSION = "2026-07-28"
export const MCP_JSON_SCHEMA_2020_12_DIALECT = "https://json-schema.org/draft/2020-12/schema"
export const MCP_UNSUPPORTED_PROTOCOL_VERSION_ERROR = { code: -32022, message: "Unsupported protocol version" } as const

export const ACP_AGENT_METHODS = [
  "initialize",
  "session/inject",
  "session/inject_host_event",
  "session/new",
  "session/load",
  "session/replace_inject",
  "session/resume",
  "session/prompt",
  "session/revoke_inject",
  "session/truncate",
  "session/rollback",
  "session/redo",
  "session/remind",
  "session/pending_injections",
  "session/revoke_reminder",
  "session/cancel_tool_call",
  "session/close",
  "session/stop",
] as const
export type ACPAgentMethod = (typeof ACP_AGENT_METHODS)[number]

export const ACP_AGENT_METHOD = {
  initialize: "initialize",
  sessionInject: "session/inject",
  sessionInjectHostEvent: "session/inject_host_event",
  sessionNew: "session/new",
  sessionLoad: "session/load",
  sessionReplaceInject: "session/replace_inject",
  sessionResume: "session/resume",
  sessionPrompt: "session/prompt",
  sessionRevokeInject: "session/revoke_inject",
  sessionTruncate: "session/truncate",
  sessionRollback: "session/rollback",
  sessionRedo: "session/redo",
  sessionRemind: "session/remind",
  sessionPendingInjections: "session/pending_injections",
  sessionRevokeReminder: "session/revoke_reminder",
  sessionCancelToolCall: "session/cancel_tool_call",
  sessionClose: "session/close",
  /** @deprecated Use session/close; session/stop will be removed after one release. */
  sessionStop: "session/stop",
} as const

export const ACP_CLIENT_METHODS = [
  "fs/read_text_file",
  "fs/write_text_file",
  "terminal/create",
  "terminal/kill",
  "session/request_permission",
] as const
export type ACPClientMethod = (typeof ACP_CLIENT_METHODS)[number]

export const ACP_AGENT_NOTIFICATIONS = [
  "session/message",
  "session/update",
  "terminal/output",
] as const
export type ACPAgentNotification = (typeof ACP_AGENT_NOTIFICATIONS)[number]

export const ACP_SESSION_UPDATES = [
  "user_message",
  "user_message_chunk",
  "agent_message_chunk",
  "agent_thought_chunk",
  "tool_call",
  "tool_call_update",
  "plan",
  "available_commands_update",
  "current_mode_update",
  "config_option_update",
  "session_info_update",
  "session_redo",
  "session_rollback",
  "session_truncated",
  "artifact",
  "fs_watch",
  "handoff",
  "hitl_request",
  "hitl_resolved",
  "live_session_client",
  "log",
  "progress",
  "reminder_emitted",
  "skill_activated",
  "skill_deactivated",
  "skill_narrow",
  "skill_scope_tools",
  "stance_transition",
  "tool_search_query",
  "tool_search_result",
  "transcript_compacted",
  "transcript_projected",
  "worker_update",
] as const
export type ACPSessionUpdate = (typeof ACP_SESSION_UPDATES)[number]

export const HARN_ACP_SESSION_UPDATE_EXTENSIONS = [
  "artifact",
  "available_commands_update",
  "fs_watch",
  "handoff",
  "hitl_request",
  "hitl_resolved",
  "live_session_client",
  "log",
  "progress",
  "reminder_emitted",
  "skill_activated",
  "skill_deactivated",
  "skill_narrow",
  "skill_scope_tools",
  "stance_transition",
  "tool_search_query",
  "tool_search_result",
  "transcript_compacted",
  "transcript_projected",
  "worker_update",
] as const
export type HarnACPSessionUpdateExtension = (typeof HARN_ACP_SESSION_UPDATE_EXTENSIONS)[number]

export const HARN_AGENT_EVENT_METHOD = "_harn/agentEvent"
export const HARN_PROVIDER_CATALOG_METHOD = "_harn/providerCatalog"
export const ACP_PROMPT_ERROR_DATA_SCHEMA = "harn.acp.prompt_error.v1" as const
export const AGENT_TERMINAL_CLASSES = [
  "context_overflow",
  "provider_misconfigured",
  "provider_unavailable",
  "rate_limited",
  "timeout",
  "resource_busy",
  "tool_policy_rejected",
  "host_bridge_unimplemented",
  "agent_loop_protocol_failure",
  "parse_dropped",
  "generic_throw",
] as const
export type AgentTerminalClass = (typeof AGENT_TERMINAL_CLASSES)[number]

export const AGENT_TERMINAL_KINDS = [
  "natural",
  "user_cancelled",
  "policy_budget",
  "completion_unverified",
  "policy_no_progress",
  "policy_thrash",
  "policy_guardrail",
  "policy_stop",
  "provider_error",
  "runtime_error",
  "suspended",
  "unknown",
] as const
export type AgentTerminalKind = (typeof AGENT_TERMINAL_KINDS)[number]

export const AGENT_TERMINAL_OWNERS = [
  "agent",
  "user",
  "policy",
  "provider",
  "harness",
  "unknown",
] as const
export type AgentTerminalOwner = (typeof AGENT_TERMINAL_OWNERS)[number]

export const HARN_PROMPT_RESULT_EXTENSION_FIELDS = [
  "terminal",
] as const
export type HarnPromptResultExtensionField = (typeof HARN_PROMPT_RESULT_EXTENSION_FIELDS)[number]

export const HARN_AGENT_EVENT_KINDS = [
  "boundary_failure",
  "budget_circuit_breaker",
  "budget_exhausted",
  "code_librarian_query_nl_fallback",
  "composition_child_call",
  "composition_child_result",
  "composition_error",
  "composition_finish",
  "composition_start",
  "compass_routing_decision",
  "control_outcome",
  "daemon_watchdog_tripped",
  "feedback_injected",
  "final_wrapup",
  "host_attachment",
  "host_tool_result",
  "input_guardrail_verdict",
  "iteration_end",
  "iteration_start",
  "judge_decision",
  "judge_started",
  "loop_control_decision",
  "loop_stuck",
  "mcp_auth_required",
  "mcp_catalog_changed",
  "mcp_notification",
  "model_job",
  "orchestration_decision",
  "pack_thinking_stripped",
  "progress_reported",
  "purpose_label",
  "repair_output_contract_applied",
  "require_successful_tools_violation",
  "reserved_terminal_verify",
  "scope_classifier_verdict",
  "self_consistency_tie",
  "session_closed",
  "structural_validator_decision",
  "subagent_join",
  "subagent_stop",
  "step_judge_decision",
  "tool_batch_disposition",
  "tool_call_audit",
  "tool_format_override",
  "typed_checkpoint",
] as const
export type HarnAgentEventKind = (typeof HARN_AGENT_EVENT_KINDS)[number]

export const ACP_CONTENT_BLOCK_TYPES = [
  "text",
  "resource_link",
  "resource",
  "image",
  "audio",
] as const
export type ACPContentBlockType = (typeof ACP_CONTENT_BLOCK_TYPES)[number]

export const ACP_TOOL_KINDS = [
  "read",
  "edit",
  "delete",
  "move",
  "search",
  "execute",
  "think",
  "fetch",
  "other",
] as const
export type ACPToolKind = (typeof ACP_TOOL_KINDS)[number]

export const ACP_TOOL_CALL_STATUSES = [
  "pending",
  "in_progress",
  "completed",
  "failed",
] as const
export type ACPToolCallStatus = (typeof ACP_TOOL_CALL_STATUSES)[number]

export const HARN_TOOL_CALL_ERROR_CATEGORIES = [
  "schema_validation",
  "tool_error",
  "mcp_server_error",
  "host_bridge_error",
  "permission_denied",
  "rejected_loop",
  "parse_aborted",
  "timeout",
  "network",
  "resource_busy",
  "cancelled",
  "abandoned_at_loop_exit",
  "environment",
  "unknown",
] as const
export type HarnToolCallErrorCategory = (typeof HARN_TOOL_CALL_ERROR_CATEGORIES)[number]

export const HARN_TOOL_MUTATION_STATUSES = [
  "applied",
  "unchanged",
  "not_applied",
  "unknown",
] as const
export type HarnToolMutationStatus = (typeof HARN_TOOL_MUTATION_STATUSES)[number]

export const HARN_SIDE_EFFECT_LEVELS = [
  "none",
  "read_only",
  "workspace_write",
  "process_exec",
  "network",
  "desktop_control",
] as const
export type HarnSideEffectLevel = (typeof HARN_SIDE_EFFECT_LEVELS)[number]

export const HARN_COMPLETION_EVIDENCE_ROLES = [
  "observation",
  "mutation",
  "verification",
] as const
export type HarnCompletionEvidenceRole = (typeof HARN_COMPLETION_EVIDENCE_ROLES)[number]

export const HARN_WORKER_STATUSES = [
  "running",
  "progressed",
  "awaiting_input",
  "suspended",
  "completed",
  "failed",
  "stopped",
  "cancelled",
] as const
export type HarnWorkerStatus = (typeof HARN_WORKER_STATUSES)[number]

export const HARN_AGENT_LIFECYCLE_STATES = [
  "running",
  "progressed",
  "awaiting_input",
  "suspended",
  "completed",
  "failed",
  "stopped",
  "cancelled",
] as const
export type HarnAgentLifecycleState = (typeof HARN_AGENT_LIFECYCLE_STATES)[number]

export const HARN_AGENT_LIFECYCLE_EVENTS = [
  "Spawned",
  "Progressed",
  "WaitingForInput",
  "Suspended",
  "Resumed",
  "Completed",
  "Failed",
  "Stopped",
  "Cancelled",
  "Joined",
] as const
export type HarnAgentLifecycleEvent = (typeof HARN_AGENT_LIFECYCLE_EVENTS)[number]

export const HARN_TOOL_CALL_RECEIPT_STATUSES = [
  "ok",
  "schema_violation",
  "consent_denied",
  "timeout",
  "error",
] as const
export type HarnToolCallReceiptStatus = (typeof HARN_TOOL_CALL_RECEIPT_STATUSES)[number]

export const HARN_TOOL_CALL_RECEIPT_EXECUTORS = [
  "harn",
  "host_bridge",
  "mcp_server",
  "provider_native",
] as const
export type HarnToolCallReceiptExecutor = (typeof HARN_TOOL_CALL_RECEIPT_EXECUTORS)[number]

export const EXTERNAL_ACTION_OUTCOMES = [
  "confirmed",
  "denied",
  "failed_before_dispatch",
  "rejected",
  "indeterminate",
] as const
export type HarnExternalActionOutcome = (typeof EXTERNAL_ACTION_OUTCOMES)[number]

export const EXTERNAL_ACTION_RECEIPT_STATUSES = [
  "confirmed",
  "denied",
  "failed_before_dispatch",
  "rejected",
  "reconciliation_required",
] as const
export type HarnExternalActionReceiptStatus = (typeof EXTERNAL_ACTION_RECEIPT_STATUSES)[number]

export const EXTERNAL_ACTION_NEXT_ACTIONS = [
  "none",
  "reconcile",
] as const
export type HarnExternalActionNextAction = (typeof EXTERNAL_ACTION_NEXT_ACTIONS)[number]

export const EXTERNAL_ACTION_ENVIRONMENTS = [
  "mock",
  "test",
  "live",
] as const
export type HarnExternalActionEnvironment = (typeof EXTERNAL_ACTION_ENVIRONMENTS)[number]

export const EXTERNAL_ACTION_AUTHORIZATION_METHODS = [
  "manual",
  "policy",
  "adversarial_auto",
  "managed_policy",
  "test_fixture",
] as const
export type HarnExternalActionAuthorizationMethod = (typeof EXTERNAL_ACTION_AUTHORIZATION_METHODS)[number]

export const EXTERNAL_ACTION_AUTHENTICATION_ASSURANCES = [
  "none",
  "session",
  "biometric",
  "managed",
] as const
export type HarnExternalActionAuthenticationAssurance = (typeof EXTERNAL_ACTION_AUTHENTICATION_ASSURANCES)[number]

export const EXTERNAL_ACTION_DISCLOSURE_SOURCES = [
  "user_profile",
  "fictional_test_fixture",
] as const
export type HarnExternalActionDisclosureSource = (typeof EXTERNAL_ACTION_DISCLOSURE_SOURCES)[number]

export const EXTERNAL_ACTION_ERROR_KINDS = [
  "invalid_intent",
  "invalid_grant",
  "invalid_policy",
  "adapter_unavailable",
  "adapter_failure",
  "malformed_adapter_result",
  "disclosure_unavailable",
  "disclosure_refused",
  "malformed_disclosure",
  "invalid_reconciliation",
] as const
export type HarnExternalActionErrorKind = (typeof EXTERNAL_ACTION_ERROR_KINDS)[number]

export const EXTERNAL_ACTION_PROTECTED_FIELD_CLASSES = [
  "legal_identity",
  "birth_date",
  "contact_details",
  "accessibility_needs",
  "loyalty_accounts",
  "travel_documents",
] as const
export type HarnExternalActionProtectedFieldClass = (typeof EXTERNAL_ACTION_PROTECTED_FIELD_CLASSES)[number]

export const EXTERNAL_ACTION_PASSENGER_GENDERS = [
  "m",
  "f",
] as const
export type HarnExternalActionPassengerGender = (typeof EXTERNAL_ACTION_PASSENGER_GENDERS)[number]

export const EXTERNAL_ACTION_ACTIVITY_STATUSES = [
  "proposed",
  "approval_pending",
  "denied",
  "cancelled",
  "timed_out",
  "dispatch_pending",
  "confirmed",
  "failed_before_dispatch",
  "rejected",
  "reconciliation_required",
] as const
export type HarnExternalActionActivityStatus = (typeof EXTERNAL_ACTION_ACTIVITY_STATUSES)[number]

export const EXTERNAL_ACTION_TERMINAL_ACTIVITY_STATUSES = [
  "denied",
  "cancelled",
  "timed_out",
  "confirmed",
  "failed_before_dispatch",
  "rejected",
] as const satisfies readonly HarnExternalActionActivityStatus[]

export function isExternalActionActivityStatusTerminal(
  status: HarnExternalActionActivityStatus,
): boolean {
  return (EXTERNAL_ACTION_TERMINAL_ACTIVITY_STATUSES as readonly string[]).includes(status)
}

export const EXTERNAL_ACTION_PROGRESS_ACTIVITY_STATUSES = [
  "proposed",
  "approval_pending",
  "dispatch_pending",
  "reconciliation_required",
] as const satisfies readonly HarnExternalActionActivityStatus[]

export function canExternalActionActivityStatusAdvance(
  current: HarnExternalActionActivityStatus,
  next: HarnExternalActionActivityStatus,
): boolean {
  if (isExternalActionActivityStatusTerminal(current)) return current === next
  if (isExternalActionActivityStatusTerminal(next)) return true
  return EXTERNAL_ACTION_PROGRESS_ACTIVITY_STATUSES.indexOf(current as never)
    <= EXTERNAL_ACTION_PROGRESS_ACTIVITY_STATUSES.indexOf(next as never)
}

export const EXTERNAL_ACTION_POLICY_LAYERS = [
  "user_policy",
  "managed_policy",
  "adversarial_reviewer",
  "remembered_rule",
] as const
export type HarnExternalActionPolicyLayer = (typeof EXTERNAL_ACTION_POLICY_LAYERS)[number]

export const EXTERNAL_ACTION_POLICY_EVALUATION_OUTCOMES = [
  "allowed",
  "denied",
  "approval_required",
  "unavailable",
] as const
export type HarnExternalActionPolicyEvaluationOutcome = (typeof EXTERNAL_ACTION_POLICY_EVALUATION_OUTCOMES)[number]

export const EXTERNAL_ACTION_DECISION_OUTCOMES = [
  "approved",
  "denied",
  "timed_out",
  "cancelled",
] as const
export type HarnExternalActionDecisionOutcome = (typeof EXTERNAL_ACTION_DECISION_OUTCOMES)[number]

export const EXTERNAL_ACTION_DECIDERS = [
  "person",
  "remembered_rule",
  "user_policy",
  "managed_policy",
  "adversarial_reviewer",
  "test_fixture",
] as const
export type HarnExternalActionDecider = (typeof EXTERNAL_ACTION_DECIDERS)[number]

export const EXTERNAL_ACTION_RECONCILIATION_STATUSES = [
  "not_needed",
  "confirmed",
  "rejected",
  "indeterminate",
  "refused",
] as const
export type HarnExternalActionReconciliationStatus = (typeof EXTERNAL_ACTION_RECONCILIATION_STATUSES)[number]

export interface HarnExternalActionActor {
  kind: string
  id: string
}

export interface HarnExternalActionMoney {
  currency: string
  amount_minor: number
}

export interface HarnExternalActionDisclosureReceipt {
  recipient: string
  purpose: string
  field_classes: HarnExternalActionProtectedFieldClass[]
  source: HarnExternalActionDisclosureSource
  authentication_assurance: HarnExternalActionAuthenticationAssurance
}

export interface HarnExternalActionError {
  kind: HarnExternalActionErrorKind
  code: string
  message: string
  retryable: boolean
}

export interface HarnExternalActionReceiptReconciliation {
  attempt_id: string
  previous_receipt_id: string
}

export interface HarnExternalActionRetryLink {
  schema: "harn.external_action_retry_link.v1"
  previous_action_id: string
  previous_receipt_id: string
}

export interface HarnExternalActionReceipt {
  schema: "harn.external_action_receipt.v1"
  id: string
  action_id: string
  effect_fingerprint?: string
  intent_fingerprint: string
  idempotency_key: string
  provider: string
  capability: string
  operation: string
  environment: HarnExternalActionEnvironment
  adapter_id: string
  outcome: HarnExternalActionOutcome
  status: HarnExternalActionReceiptStatus
  next_action: HarnExternalActionNextAction
  dispatch_attempted: boolean
  recorded_at_ms: number
  provider_action_id?: string
  evidence_refs: string[]
  error?: HarnExternalActionError
  reconciliation?: HarnExternalActionReceiptReconciliation
  disclosure?: HarnExternalActionDisclosureReceipt
  retry?: HarnExternalActionRetryLink
}

export interface HarnExternalActionPolicyEvaluation {
  layer: HarnExternalActionPolicyLayer
  outcome: HarnExternalActionPolicyEvaluationOutcome
  reason_code: string
  policy_id?: string
}

export interface HarnExternalActionDecision {
  outcome: HarnExternalActionDecisionOutcome
  decider: HarnExternalActionDecider
  decided_at_ms: number
  reason_code: string
  actor?: HarnExternalActionActor
}

export interface HarnExternalActionAuthorizationRecord {
  method: HarnExternalActionAuthorizationMethod
  authentication_assurance: HarnExternalActionAuthenticationAssurance
  issued_at_ms: number
  expires_at_ms: number
}

export interface HarnExternalActionRequester {
  actor: HarnExternalActionActor
  agent_id?: string
  model_provider?: string
  model_id?: string
  session_id?: string
  run_id?: string
}

export interface HarnExternalActionDispatchRecord {
  attempted: boolean
  adapter_id?: string
}

export interface HarnExternalActionReconciliationRecord {
  attempted: boolean
  status: HarnExternalActionReconciliationStatus
  attempt_id?: string
  previous_receipt_id?: string
}

export interface HarnExternalActionActivityRecord {
  schema: "harn.external_action_activity.v1"
  kind: "external_action"
  id: string
  action_id: string
  effect_fingerprint?: string
  intent_fingerprint: string
  provider: string
  capability: string
  operation: string
  environment: HarnExternalActionEnvironment
  summary: string
  external_spend?: HarnExternalActionMoney
  status: HarnExternalActionActivityStatus
  updated_at_ms: number
  requester: HarnExternalActionRequester
  policy_evaluations: HarnExternalActionPolicyEvaluation[]
  decision?: HarnExternalActionDecision
  authorization?: HarnExternalActionAuthorizationRecord
  disclosure?: HarnExternalActionDisclosureReceipt
  dispatch: HarnExternalActionDispatchRecord
  reconciliation?: HarnExternalActionReconciliationRecord
  receipt?: HarnExternalActionReceipt
  retry?: HarnExternalActionRetryLink
}

export const ACTIVITY_KINDS = [
  "external_action",
  "tool_permission",
] as const
export type HarnActivityKind = (typeof ACTIVITY_KINDS)[number]

export const TOOL_PERMISSION_OUTCOMES = [
  "approved",
  "denied",
  "timed_out",
  "cancelled",
] as const
export type HarnToolPermissionOutcome = (typeof TOOL_PERMISSION_OUTCOMES)[number]

export const TOOL_PERMISSION_DECIDERS = [
  "person",
  "remembered_rule",
  "user_policy",
  "managed_policy",
  "runtime_policy",
  "host_unavailable",
  "auto_reviewer",
] as const
export type HarnToolPermissionDecider = (typeof TOOL_PERMISSION_DECIDERS)[number]

export const TOOL_PERMISSION_POLICY_LAYERS = [
  "user_policy",
  "managed_policy",
  "runtime_policy",
  "remembered_rule",
] as const
export type HarnToolPermissionPolicyLayer = (typeof TOOL_PERMISSION_POLICY_LAYERS)[number]

export const TOOL_PERMISSION_POLICY_OUTCOMES = [
  "allowed",
  "denied",
  "approval_required",
  "unavailable",
] as const
export type HarnToolPermissionPolicyOutcome = (typeof TOOL_PERMISSION_POLICY_OUTCOMES)[number]

export const TOOL_PERMISSION_GRANT_SCOPES = [
  "once",
  "session",
] as const
export type HarnToolPermissionGrantScope = (typeof TOOL_PERMISSION_GRANT_SCOPES)[number]

export const TOOL_PERMISSION_GRANT_EXPIRIES = [
  "after_dispatch",
  "session_end",
] as const
export type HarnToolPermissionGrantExpiry = (typeof TOOL_PERMISSION_GRANT_EXPIRIES)[number]

export interface HarnToolPermissionScope {
  tool_kind: ACPToolKind
  side_effect: HarnSideEffectLevel
  capabilities: string[]
}

export interface HarnToolPermissionPolicyEvidence {
  layer: HarnToolPermissionPolicyLayer
  outcome: HarnToolPermissionPolicyOutcome
  rule_id?: string
  risk_labels: string[]
}

export interface HarnToolPermissionDecisionMetadata {
  schema: "harn.tool_permission_decision.v1"
  outcome: HarnToolPermissionOutcome
  decider: HarnToolPermissionDecider
  policy_evaluations: HarnToolPermissionPolicyEvidence[]
  grant_scope?: HarnToolPermissionGrantScope
}

export interface HarnToolPermissionGrantEvidence {
  scope: HarnToolPermissionGrantScope
  expires: HarnToolPermissionGrantExpiry
  reusable: false
}

export interface HarnToolPermissionRequester {
  session_id: string
  agent_id?: string
  model_provider?: string
  model_id?: string
}

export interface HarnToolPermissionActivityRecord {
  schema: "harn.tool_permission_activity.v1"
  kind: "tool_permission"
  id: string
  request_id: string
  tool_name: string
  scope: HarnToolPermissionScope
  outcome: HarnToolPermissionOutcome
  decider: HarnToolPermissionDecider
  policy_evaluations: HarnToolPermissionPolicyEvidence[]
  grant?: HarnToolPermissionGrantEvidence
  requester: HarnToolPermissionRequester
  occurred_at_ms: number
}

export const CONNECTOR_SETUP_STAGES = [
  "resolving",
  "opening_browser",
  "waiting_for_user",
  "exchanging",
  "storing",
  "validating",
  "ready",
] as const
export type HarnConnectorSetupStage = (typeof CONNECTOR_SETUP_STAGES)[number]

export const CONNECTOR_SETUP_STATUSES = [
  "in_progress",
  "succeeded",
  "failed",
  "cancelled",
  "timed_out",
] as const
export type HarnConnectorSetupStatus = (typeof CONNECTOR_SETUP_STATUSES)[number]

export const CONNECTOR_SETUP_INTERACTIONS = [
  "none",
  "browser",
  "secret_entry",
  "user_code",
] as const
export type HarnConnectorSetupInteraction = (typeof CONNECTOR_SETUP_INTERACTIONS)[number]

export const CONNECTOR_SETUP_CONFIGURATION_FIELDS = [
  "oauth_client_id",
] as const
export type HarnConnectorSetupConfigurationField = (typeof CONNECTOR_SETUP_CONFIGURATION_FIELDS)[number]

export const CONNECTOR_SETUP_ERROR_CODES = [
  "connector_unavailable",
  "configuration_missing",
  "browser_open_failed",
  "callback_timeout",
  "user_denied",
  "state_mismatch",
  "token_exchange_failed",
  "credential_store_failed",
  "validation_failed",
  "cancelled",
  "unknown",
] as const
export type HarnConnectorSetupErrorCode = (typeof CONNECTOR_SETUP_ERROR_CODES)[number]

export interface HarnConnectorSetupEvent {
  schema: "harn.connector_setup.event.v1"
  sequence: number
  connector: string
  stage: HarnConnectorSetupStage
  status: HarnConnectorSetupStatus
  interaction: HarnConnectorSetupInteraction
  message: string
  error_code?: HarnConnectorSetupErrorCode
  recovery?: string
}

export const A2A_TASK_STATES = [
  "submitted",
  "working",
  "completed",
  "failed",
  "canceled",
  "cancelled",
  "input-required",
  "rejected",
  "auth-required",
] as const
export type A2ATaskState = (typeof A2A_TASK_STATES)[number]

export const A2A_TASK_EVENT_TYPES = [
  "status",
  "message",
  "worker_update",
] as const
export type A2ATaskEventType = (typeof A2A_TASK_EVENT_TYPES)[number]

export const MCP_PROTOCOL_VERSIONS = [
  "2026-07-28",
] as const
export type MCPProtocolVersion = (typeof MCP_PROTOCOL_VERSIONS)[number]

export const MCP_METHODS = [
  "server/discover",
  "tools/list",
  "tools/call",
  "resources/list",
  "resources/read",
  "resources/templates/list",
  "prompts/list",
  "prompts/get",
  "completion/complete",
  "sampling/createMessage",
  "elicitation/create",
  "notifications/message",
  "tasks/get",
  "tasks/update",
  "tasks/cancel",
] as const
export type MCPMethod = (typeof MCP_METHODS)[number]

export const MCP_REQUIRED_METADATA_KEYS = [
  "io.modelcontextprotocol/protocolVersion",
  "io.modelcontextprotocol/clientInfo",
  "io.modelcontextprotocol/clientCapabilities",
] as const
export type MCPRequiredMetadataKey = (typeof MCP_REQUIRED_METADATA_KEYS)[number]

export const MCP_METADATA_KEYS = [
  "io.modelcontextprotocol/protocolVersion",
  "io.modelcontextprotocol/clientInfo",
  "io.modelcontextprotocol/clientCapabilities",
  "io.modelcontextprotocol/logLevel",
  "progressToken",
  "traceparent",
  "tracestate",
  "baggage",
] as const
export type MCPMetadataKey = (typeof MCP_METADATA_KEYS)[number]

export const MCP_STANDARD_HTTP_HEADERS = [
  "MCP-Protocol-Version",
  "Mcp-Method",
  "Mcp-Name",
] as const
export type MCPStandardHTTPHeader = (typeof MCP_STANDARD_HTTP_HEADERS)[number]

export const MCP_CACHE_RESULT_FIELDS = [
  "ttlMs",
  "cacheScope",
] as const
export type MCPCacheResultField = (typeof MCP_CACHE_RESULT_FIELDS)[number]

export const MCP_CACHE_SCOPES = [
  "private",
  "public",
] as const
export type MCPCacheScope = (typeof MCP_CACHE_SCOPES)[number]

export const MCP_RESULT_TYPES = [
  "complete",
  "input_required",
  "task",
] as const
export type MCPResultType = (typeof MCP_RESULT_TYPES)[number]

export const MCP_LOGGING_LEVELS = [
  "debug",
  "info",
  "notice",
  "warning",
  "error",
  "critical",
  "alert",
  "emergency",
] as const
export type MCPLoggingLevel = (typeof MCP_LOGGING_LEVELS)[number]

export const MCP_OAUTH_CLIENT_REGISTRATION_MODES = [
  "pre_registered",
  "client_id_metadata_document",
  "dynamic_client_registration",
  "manual",
] as const
export type MCPOAuthClientRegistrationMode = (typeof MCP_OAUTH_CLIENT_REGISTRATION_MODES)[number]

export const MCP_OAUTH_AUTH_MODES = [
  "cimd",
  "dcr",
  "static",
  "byo",
] as const
export type MCPOAuthAuthMode = (typeof MCP_OAUTH_AUTH_MODES)[number]

export const MCP_OAUTH_APPLICATION_TYPES = [
  "native",
  "web",
] as const
export type MCPOAuthApplicationType = (typeof MCP_OAUTH_APPLICATION_TYPES)[number]


export type ACPObject = { [key: string]: ACPValue }
export type ACPValue = null | boolean | number | string | ACPValue[] | ACPObject
export type JsonRpcId = number | string | null

export type HarnPlanStepStatus = "pending" | "in_progress" | "completed" | "blocked" | "cancelled"
export type HarnPlanApprovalState = "unrequested" | "requested" | "approved" | "rejected"
export type HarnPlanCommentState = "open" | "addressed" | "resolved" | "reopened"

export interface HarnPlanAuthor {
  id: string
  display_name?: string
}

export interface HarnPlanSource {
  kind: string
  uri?: string
}

export interface HarnPlanStep {
  id: string
  content: string
  status: HarnPlanStepStatus
  priority?: ACPValue
}

export interface HarnPlanApproval {
  state: HarnPlanApprovalState
  request_id?: string
  reviewer?: string
  reviewers?: string[]
  approved_at?: string
  reason?: string
}

export interface HarnPlanArtifact {
  _type: "plan_artifact"
  schema_version: "harn.plan.v1"
  id: string
  tool: string
  title: string
  summary: string
  steps: HarnPlanStep[]
  assumptions: string[]
  open_questions: string[]
  verification_commands: string[]
  approval: HarnPlanApproval
}

export interface HarnPlanRevision {
  revision_id: string
  parent_revision_id?: string
  markdown: string
  plan: HarnPlanArtifact
  author: HarnPlanAuthor
  source: HarnPlanSource
  created_at: string
  operation:
    | { kind: "create" | "edit"; event_id: string }
    | { kind: "comment"; event_id: string; comment_id: string }
    | { kind: "comment_state"; event_id: string; comment_id: string; state: HarnPlanCommentState }
}

export interface HarnPlanCommentAnchor {
  step_id?: string
  quoted_text?: string
  range?: { start: number; end: number }
}

export interface HarnPlanComment {
  comment_id: string
  anchor: HarnPlanCommentAnchor
  body: string
  state: HarnPlanCommentState
  author: HarnPlanAuthor
  created_at: string
  updated_at: string
}

export interface HarnPlanCommentResolutionReceipt {
  receipt_id: string
  comment_id: string
  input_revision_id: string
  output_revision_id: string
  agent_run_id: string
  event_id: string
  explanation?: string
  created_at: string
}

export interface HarnPlanDocument {
  _type: "plan_document"
  schema_version: "harn.plan_document.v1"
  document_id: string
  current_revision: HarnPlanRevision
  comments: HarnPlanComment[]
  resolution_receipts: HarnPlanCommentResolutionReceipt[]
  created_at: string
  updated_at: string
}

export interface ACPRequest {
  jsonrpc: "2.0"
  id: Exclude<JsonRpcId, null>
  method: string
  params?: ACPValue
}

export interface ACPResponse {
  jsonrpc: "2.0"
  id: JsonRpcId
  result?: ACPValue
  error?: ACPError
}

export interface ACPError {
  code: number
  message: string
  data?: ACPValue
}

export interface HarnACPPromptErrorData {
  schema: typeof ACP_PROMPT_ERROR_DATA_SCHEMA
  terminalClass: AgentTerminalClass
  category?: string
  kind?: string
  reason?: string
  code?: string
  retryable?: boolean
  retryAfterMs?: number
  provider?: string
  model?: string
}

export interface HarnAgentTerminalOutcome {
  kind: AgentTerminalKind
  reason: string
  owner: AgentTerminalOwner
  terminalClass?: AgentTerminalClass
  message?: string
  detail?: string
}

export interface HarnACPPromptResult {
  stopReason: string
  _meta?: {
    harn: {
      terminal?: HarnAgentTerminalOutcome
    }
  }
}

export interface ACPNotification {
  jsonrpc: "2.0"
  method: string
  params?: ACPValue
}

export type ACPMessage = ACPRequest | ACPResponse | ACPNotification

export type HarnHostInjectionKind = "host_tool_result" | "host_attachment"
export type HarnHostInjectionDelivery =
  | "turn_boundary"
  | "immediate"
  | "after_next_tool_call"

export interface HarnHostInjectionProvenance {
  initiator: string
  source: string
  host?: string
  ts_ms: number
}

export interface HarnHostInjectionEvent {
  kind: HarnHostInjectionKind
  delivery?: HarnHostInjectionDelivery
  payload: ACPObject
  provenance: HarnHostInjectionProvenance
}

export interface ACPSessionInjectHostEventParams {
  sessionId: string
  event: HarnHostInjectionEvent
}

export interface ACPExtensionMeta<T extends object = ACPObject> {
  harn?: T
}

export interface ACPContentBlock {
  type: "text" | "resource_link" | "resource" | "image" | "audio" | string
  text?: string
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPToolCallDiff {
  type: "diff"
  path: string
  oldText?: string | null
  newText: string
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPToolCallContentBlock {
  type: "content"
  content: ACPContentBlock
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPToolCallTerminal {
  type: "terminal"
  terminalId: string
  _meta?: ACPExtensionMeta<ACPObject>
}

export type ACPToolCallContent =
  | ACPToolCallDiff
  | ACPToolCallContentBlock
  | ACPToolCallTerminal

export type ACPToolExecutor =
  | "harn_builtin"
  | "host_bridge"
  | "provider_native"
  | { kind: "mcp_server"; serverName: string }

export interface HarnToolLifecycleMeta {
  audit?: ACPValue
  changedPaths?: string[]
  data?: ACPValue
  durationMs?: number
  error?: string
  errorCategory?: HarnToolCallErrorCategory
  executionDurationMs?: number
  executor?: ACPToolExecutor
  mutationStatus?: HarnToolMutationStatus
  parsing?: boolean
  rawInputPartial?: string
}

export interface ToolCallReceipt {
  schema_version: number
  session_id: string
  run_id: string | null
  tool_call_id: string
  tool_name: string
  iteration: number
  turn_index: number | null
  emit_order: number
  reason: string | null
  kind: string | null
  executor: HarnToolCallReceiptExecutor | null
  status: HarnToolCallReceiptStatus
  error_category: string | null
  duration_ms: number
  args_hash: string
  result_hash: string | null
  audit: ACPValue
  emitted_at: string
  model: string | null
  provider: string | null
}

export interface ACPToolCall {
  sessionUpdate: "tool_call"
  toolCallId: string
  title: string
  kind?: ACPToolKind
  status?: ACPToolCallStatus
  content?: ACPToolCallContent[]
  locations?: ACPValue[]
  rawInput?: ACPValue
  rawOutput?: ACPValue
  _meta?: ACPExtensionMeta<HarnToolLifecycleMeta>
}

export interface ACPToolCallUpdate {
  sessionUpdate: "tool_call_update"
  toolCallId: string
  title?: string | null
  kind?: ACPToolKind
  status?: ACPToolCallStatus | null
  content?: ACPToolCallContent[]
  locations?: ACPValue[]
  rawInput?: ACPValue
  rawOutput?: ACPValue
  _meta?: ACPExtensionMeta<HarnToolLifecycleMeta>
}

export interface ACPMessageChunkUpdate {
  sessionUpdate: "agent_message_chunk" | "agent_thought_chunk" | "user_message_chunk"
  content: ACPContentBlock
}

export interface ACPUserMessageUpdate {
  sessionUpdate: "user_message"
  messageId: string
  content: ACPContentBlock[]
}

export interface ACPPlanUpdate {
  sessionUpdate: "plan"
  entries: ACPValue[]
  harnPlanDocument?: HarnPlanDocument
}

export interface ACPSessionTruncatedUpdate {
  sessionUpdate: "session_truncated"
  keptTurnCount: number
  removedTurnCount: number
  newTipTurnId?: string | null
  reason?: string
}

/** Harn-owned `session/update` extension payloads. Identity fields are first-class; `_meta` remains for vendor extras. */
export const HARN_TYPED_SESSION_UPDATE_PAYLOADS = {
  artifact: { typeName: "ACPArtifactUpdate", identity: ["artifactId"] },
  available_commands_update: { typeName: "ACPAvailableCommandsUpdate", identity: ["availableCommands"] },
  fs_watch: { typeName: "ACPFsWatchUpdate", identity: ["subscriptionId", "events"] },
  handoff: { typeName: "ACPHandoffUpdate", identity: ["handoffId", "artifactId", "handoff"] },
  hitl_request: { typeName: "ACPHitlRequestUpdate", identity: ["requestId"] },
  hitl_resolved: { typeName: "ACPHitlResolvedUpdate", identity: ["requestId"] },
  live_session_client: { typeName: "ACPLiveSessionClientUpdate", identity: ["action"] },
  log: { typeName: "ACPLogUpdate", identity: ["message"] },
  progress: { typeName: "ACPProgressUpdate", identity: ["message"] },
  reminder_emitted: { typeName: "ACPReminderEmittedUpdate", identity: ["reminderId"] },
  skill_activated: { typeName: "ACPSkillActivatedUpdate", identity: ["skillName"] },
  skill_deactivated: { typeName: "ACPSkillDeactivatedUpdate", identity: ["skillName"] },
  skill_narrow: { typeName: "ACPSkillNarrowUpdate", identity: ["removedTools", "remainingTools"] },
  skill_scope_tools: { typeName: "ACPSkillScopeToolsUpdate", identity: ["skillName", "allowedTools"] },
  stance_transition: { typeName: "ACPStanceTransitionUpdate", identity: ["phase"] },
  tool_search_query: { typeName: "ACPToolSearchQueryUpdate", identity: ["toolUseId", "name"] },
  tool_search_result: { typeName: "ACPToolSearchResultUpdate", identity: ["toolUseId"] },
  transcript_compacted: { typeName: "ACPTranscriptCompactedUpdate", identity: ["mode", "strategy"] },
  transcript_projected: { typeName: "ACPTranscriptProjectedUpdate", identity: ["policy"] },
  worker_update: { typeName: "ACPWorkerUpdate", identity: ["workerId", "event", "status"] },
} as const

export interface ACPArtifactUpdate {
  sessionUpdate: "artifact"
  artifactId: string
  kind?: string
  title?: string
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPAvailableCommandsUpdate {
  sessionUpdate: "available_commands_update"
  availableCommands: ACPValue
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPFsWatchUpdate {
  sessionUpdate: "fs_watch"
  subscriptionId: string
  events: ACPValue
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPHandoffUpdate {
  sessionUpdate: "handoff"
  handoffId: string
  artifactId: string
  handoff: ACPValue
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPHitlRequestUpdate {
  sessionUpdate: "hitl_request"
  requestId: string
  kind: string
  payload: ACPValue
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPHitlResolvedUpdate {
  sessionUpdate: "hitl_resolved"
  requestId: string
  kind: string
  outcome: ACPValue
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPLiveSessionClientUpdate {
  sessionUpdate: "live_session_client"
  action: string
  state?: ACPValue
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPLogUpdate {
  sessionUpdate: "log"
  message: string
  level?: string
  fields?: ACPValue
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPProgressUpdate {
  sessionUpdate: "progress"
  message: string
  phase?: string
  progress?: number
  total?: number
  data?: ACPValue
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPReminderEmittedUpdate {
  sessionUpdate: "reminder_emitted"
  reminderId: string
  reminder?: ACPValue
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPSkillActivatedUpdate {
  sessionUpdate: "skill_activated"
  skillName: string
  iteration?: number
  reason?: string
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPSkillDeactivatedUpdate {
  sessionUpdate: "skill_deactivated"
  skillName: string
  iteration?: number
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPSkillNarrowUpdate {
  sessionUpdate: "skill_narrow"
  removedTools: string[]
  remainingTools: string[]
  reason?: string
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPSkillScopeToolsUpdate {
  sessionUpdate: "skill_scope_tools"
  skillName: string
  allowedTools: string[]
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPStanceTransitionUpdate {
  sessionUpdate: "stance_transition"
  phase: string
  escapeTool?: string
  allowedTools?: string[]
  justification?: string
  consent?: string
  reason?: string
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPToolSearchQueryUpdate {
  sessionUpdate: "tool_search_query"
  toolUseId: string
  name: string
  query: ACPValue
  strategy?: string
  mode?: string
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPToolSearchResultUpdate {
  sessionUpdate: "tool_search_result"
  toolUseId: string
  promoted: ACPValue
  strategy?: string
  mode?: string
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPTranscriptCompactedUpdate {
  sessionUpdate: "transcript_compacted"
  mode: string
  strategy: string
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPTranscriptProjectedUpdate {
  sessionUpdate: "transcript_projected"
  policy: string
  reason: string
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPWorkerUpdate {
  sessionUpdate: "worker_update"
  workerId: string
  event: string
  status: string
  terminal: boolean
  workerName?: string
  workerTask?: string
  workerMode?: string
  metadata?: ACPValue
  audit?: ACPValue
  _meta?: ACPExtensionMeta<ACPObject>
}

export interface ACPHarnExtensionUpdate {
  sessionUpdate: HarnACPSessionUpdateExtension
  _meta?: ACPExtensionMeta<ACPObject>
}

export type ACPSessionUpdateEnvelope =
  | ACPUserMessageUpdate
  | ACPMessageChunkUpdate
  | ACPToolCall
  | ACPToolCallUpdate
  | ACPPlanUpdate
  | ACPSessionTruncatedUpdate
  | ACPArtifactUpdate
  | ACPAvailableCommandsUpdate
  | ACPFsWatchUpdate
  | ACPHandoffUpdate
  | ACPHitlRequestUpdate
  | ACPHitlResolvedUpdate
  | ACPLiveSessionClientUpdate
  | ACPLogUpdate
  | ACPProgressUpdate
  | ACPReminderEmittedUpdate
  | ACPSkillActivatedUpdate
  | ACPSkillDeactivatedUpdate
  | ACPSkillNarrowUpdate
  | ACPSkillScopeToolsUpdate
  | ACPStanceTransitionUpdate
  | ACPToolSearchQueryUpdate
  | ACPToolSearchResultUpdate
  | ACPTranscriptCompactedUpdate
  | ACPTranscriptProjectedUpdate
  | ACPWorkerUpdate
  | ACPHarnExtensionUpdate

export interface ACPSessionUpdateParams {
  sessionId: string
  update: ACPSessionUpdateEnvelope
}

export interface ACPSessionUpdateNotification {
  jsonrpc: "2.0"
  method: "session/update"
  params: ACPSessionUpdateParams
}

export interface HarnAgentEventNotification {
  jsonrpc: "2.0"
  method: typeof HARN_AGENT_EVENT_METHOD
  params: ACPObject & {
    sessionId: string
    kind: HarnAgentEventKind
  }
}

export interface ACPPermissionToolCall {
  sessionUpdate?: "tool_call_update"
  toolCallId: string
  title?: string
  kind?: ACPToolKind
  content?: ACPToolCallContent[]
  rawInput?: ACPValue
  _meta?: ACPExtensionMeta<ACPObject>
}

export type ACPPermissionOptionKind =
  | "allow_once"
  | "allow_always"
  | "reject_once"
  | "reject_always"

export interface ACPPermissionOption {
  optionId: string
  name: string
  kind: ACPPermissionOptionKind
}

export interface ACPSessionRequestPermissionParams {
  sessionId: string
  toolCall: ACPPermissionToolCall
  options: ACPPermissionOption[]
}

export type ACPPermissionOutcome =
  | { outcome: "selected"; optionId: string }
  | { outcome: "cancelled" }

export interface ACPSessionRequestPermissionResult {
  outcome: ACPPermissionOutcome
  reason?: string
}

export interface ACPPromptCapabilities {
  image?: boolean
  audio?: boolean
  embeddedContext?: boolean
}

export interface ACPAgentCapabilities {
  _meta?: ACPExtensionMeta<{
    schemaCompatibility?: string
    sessionUpdateExtensions?: HarnACPSessionUpdateExtension[]
    toolLifecycleExtensionFields?: string[]
    contentExtensionFields?: string[]
    promptResultExtensionFields?: HarnPromptResultExtensionField[]
    extensionMethods?: Record<string, ACPObject>
    hostCapabilityOperations?: Record<string, string[]>
    extensionContract?: string
  }>
  loadSession?: boolean
  session?: ACPObject
  promptCapabilities?: ACPPromptCapabilities
  mcpCapabilities?: ACPObject
  sessionCapabilities?: ACPObject
}

export interface ACPClientCapabilities {
  fs?: {
    readTextFile?: boolean
    writeTextFile?: boolean
  }
  terminal?: {
    create?: boolean
  }
}

export interface HarnToolArgSchema {
  path_params: string[]
  dependency_key_params: string[]
  dependency_range_params: Array<Record<string, string>>
  arg_aliases: Record<string, string>
  required: string[]
}

export interface HarnToolAnnotations {
  kind: ACPToolKind
  side_effect_level: HarnSideEffectLevel
  completion_evidence_role?: HarnCompletionEvidenceRole
  arg_schema: HarnToolArgSchema
  capabilities: Record<string, string[]>
  emits_artifacts: boolean
  result_readers: string[]
  inline_result: boolean
}

export interface A2ATaskStatus {
  state: A2ATaskState
  message?: A2AMessage
  timestamp?: string
}

export interface A2ATask {
  id: string
  contextId?: string | null
  status: A2ATaskStatus
  history?: A2AMessage[]
  artifacts?: ACPValue[]
  metadata?: ACPObject
}

export interface A2AMessage {
  id: string
  role: "user" | "agent"
  parts: ACPValue[]
}

export type A2ATaskEvent =
  | { type: "status"; taskId: string; status: A2ATaskStatus }
  | { type: "message" | "worker_update"; taskId: string; message?: A2AMessage }
  | { statusUpdate: { taskId: string; contextId?: string | null; status: A2ATaskStatus } }

export type MCPJsonSchema202012 = ACPObject

export interface MCPImplementation {
  name: string
  version: string
  title?: string
  description?: string
  websiteUrl?: string
}

export interface MCPRequestMeta {
  "io.modelcontextprotocol/protocolVersion": MCPProtocolVersion | string
  "io.modelcontextprotocol/clientInfo": MCPImplementation
  "io.modelcontextprotocol/clientCapabilities": ACPObject
  "io.modelcontextprotocol/logLevel"?: MCPLoggingLevel
  progressToken?: string | number
  traceparent?: string
  tracestate?: string
  baggage?: string
  [key: string]: ACPValue | MCPImplementation | undefined
}

export interface MCPHTTPHeaders {
  "MCP-Protocol-Version": MCPProtocolVersion | string
  "Mcp-Method": MCPMethod | string
  "Mcp-Name"?: string
  [header: string]: string | undefined
}

export interface MCPCacheHints {
  ttlMs: number
  cacheScope: MCPCacheScope
}

export interface MCPDiscoverResult {
  resultType: "complete"
  supportedVersions: (MCPProtocolVersion | string)[]
  capabilities: ACPObject
  ttlMs: number
  cacheScope: MCPCacheScope
  instructions?: string
  _meta?: ACPObject
}

export interface MCPInputRequiredResult {
  resultType: "input_required"
  inputRequests?: Record<string, ACPObject>
  requestState?: string
  _meta?: ACPObject
}

export interface MCPUnsupportedProtocolVersionError {
  jsonrpc: "2.0"
  id?: JsonRpcId
  error: {
    code: typeof MCP_UNSUPPORTED_PROTOCOL_VERSION_ERROR.code
    message: typeof MCP_UNSUPPORTED_PROTOCOL_VERSION_ERROR.message
    data: {
      requested: string
      supported: (MCPProtocolVersion | string)[]
    }
  }
}

export interface MCPTool {
  name: string
  title?: string
  description?: string
  inputSchema: MCPJsonSchema202012
  outputSchema?: MCPJsonSchema202012
  annotations?: ACPObject
}

export interface MCPResource {
  uri: string
  name: string
  title?: string
  description?: string
  mimeType?: string
}

export interface MCPResourceTemplate {
  uriTemplate: string
  name: string
  title?: string
  description?: string
  mimeType?: string
}

export interface MCPPrompt {
  name: string
  title?: string
  description?: string
  arguments?: ACPObject[]
}

export interface MCPOAuthProtectedResourceMetadata {
  resource?: string
  authorization_servers: string[]
  scopes_supported?: string[]
  bearer_methods_supported?: string[]
  [key: string]: ACPValue | undefined
}

export interface MCPOAuthAuthorizationServerMetadata {
  issuer: string
  authorization_endpoint: string
  token_endpoint: string
  registration_endpoint?: string
  token_endpoint_auth_methods_supported?: string[]
  code_challenge_methods_supported?: string[]
  scopes_supported?: string[]
  client_id_metadata_document_supported?: boolean
  authorization_response_iss_parameter_supported?: boolean
  [key: string]: ACPValue | undefined
}

export interface MCPOAuthWwwAuthenticateChallenge {
  scheme: string
  params: Record<string, string>
}

export interface MCPOAuthDiscoveryResult {
  protectedResourceMetadataUrl: string
  protectedResourceMetadata: MCPOAuthProtectedResourceMetadata
  authorizationServerIssuer: string
  authorizationServerMetadataUrl: string
  authorizationServerMetadataKind: "oauth_authorization_server" | "openid_configuration"
  authorizationServerMetadata: MCPOAuthAuthorizationServerMetadata
  challenge?: MCPOAuthWwwAuthenticateChallenge
  scopes: string[]
}

export interface MCPOAuthDynamicClientRegistrationRequest {
  client_name: string
  redirect_uris: string[]
  grant_types: string[]
  response_types: string[]
  token_endpoint_auth_method: string
  application_type: MCPOAuthApplicationType
  scope?: string
}

export function isRequest(msg: ACPMessage): msg is ACPRequest {
  return "id" in msg && "method" in msg
}

export function isResponse(msg: ACPMessage): msg is ACPResponse {
  return "id" in msg && !("method" in msg)
}

export function isNotification(msg: ACPMessage): msg is ACPNotification {
  return !("id" in msg) && "method" in msg
}

export interface HarnSessionTimelineCursor {
  topics: Record<string, number>
}

export interface HarnSessionTimelineQuery {
  sessionId?: string | null
  runId?: string | null
  runPath?: string | null
  projectId?: string | null
  fromCursor: HarnSessionTimelineCursor
  limit?: number | null
}

export interface HarnSessionTimelineReference {
  kind: string
  id?: string
  topic?: string
  eventId?: number
}

export interface HarnSessionTimelineLink {
  kind: string
  targetId?: string
  traceId?: string
  spanId?: string
  eventId?: string
}

/** Harn-owned semantic chronology row. `kind` remains open for forward compatibility. */
export interface HarnSessionTimelineNode {
  id: string
  parentId?: string
  children: string[]
  category: string
  kind: string
  name: string
  status: string
  traceId?: string
  spanId?: string
  occurredAtMs?: number
  startMs?: number
  durationMs?: number
  attributes: ACPValue
  references: HarnSessionTimelineReference[]
  links: HarnSessionTimelineLink[]
  order: number
}

export interface HarnSessionTimelineCoverage {
  returned: number
  available: number | null
  truncated: boolean
}

export interface HarnSessionTimelineSnapshot {
  schemaVersion: number
  query: HarnSessionTimelineQuery
  cursor: HarnSessionTimelineCursor
  coverage: HarnSessionTimelineCoverage
  nodes: HarnSessionTimelineNode[]
}

export interface HarnSessionTimelineUpdate {
  schemaVersion: number
  cursor: HarnSessionTimelineCursor
  node: HarnSessionTimelineNode
}

export const HARN_PREPARED_SESSION_SCHEMA = "harn.prepared_session.v1" as const
export type HarnPreparedSessionState = "needs_approval" | "ready" | "blocked" | "active" | "delta" | "stopped" | "pivoted" | "terminal"
export type HarnPreparedSessionCommand = "approval_decision" | "attach" | "turn" | "request_delta" | "stop" | "pivot" | "finish"
export interface HarnPreparedSessionApprovalDecision { batch_fingerprint: string; approved: boolean; decider: string }
export interface HarnPreparedSessionBinding { session_id: string; workspace_fingerprint: string; runtime: ACPValue; consumer: ACPValue }
export interface HarnPreparedRuntimeAttachment { session_id: string; workspace_fingerprint: string; runtime: ACPValue; consumer: ACPValue }
export interface HarnPreparedSessionLease {
  schema: typeof HARN_PREPARED_SESSION_SCHEMA; session_id: string; session_fingerprint: string
  plan_fingerprint: string; binding: HarnPreparedSessionBinding; intent: ACPValue
  approval?: HarnPreparedSessionApprovalDecision | null; issued_at_ms: number; expires_at_ms: number
}
export interface HarnPreparedSessionUpdate {
  state: HarnPreparedSessionState; session_id: string; batch?: ACPValue; lease?: HarnPreparedSessionLease
  diagnostics?: ACPValue[]; receipt?: ACPValue; outcome?: ACPValue
}

export const HARN_SESSION_RECAP_QUERY_METHOD = "harn.session_recap.query" as const
export const HARN_SESSION_RECAP_SCHEMA_VERSION = 1 as const

export type HarnSessionRecapCompletionState = "open" | "complete" | "incomplete" | "unassigned"
export type HarnSessionRecapToolState = "open" | "completed" | "failed" | "incomplete"
export type HarnSessionRecapPlanStepStatus = "pending" | "in_progress" | "completed" | "blocked" | "cancelled"
export type HarnSessionRecapPlanEventKind = "created" | "updated"
export type HarnSessionRecapProgressStatus = "pending" | "in_progress" | "completed"
export type HarnSessionRecapProgressPriority = "high" | "medium" | "low"
export type HarnSessionRecapVerificationStatus = "passed"
export type HarnSessionRecapUnavailableReason = "journal_unavailable" | "session_missing" | "projection_failed" | "admission_terminal"

export interface HarnSessionRecapQuery {
  sessionId: string
  runId: string | null
  turnId: string | null
  fromEventId: number | null
  limit: number | null
}
export interface HarnSessionRecapCursor { lastEventId: number | null; nextEventId: number | null }
export interface HarnSessionRecapCoverage { scanned: number; matched: number; pending: number; unassigned: number; truncated: boolean }
export interface HarnSessionRecapSourceEvent { eventId: number; recordHash: string }
export interface HarnSessionRecapSource { firstEventId: number | null; lastEventId: number | null; events: HarnSessionRecapSourceEvent[] }
export interface HarnSessionRecapTextFact { text: string; sourceEventId: number }
export interface HarnSessionRecapVerificationFact { schema: string; status: HarnSessionRecapVerificationStatus; verifiedPaths: string[]; sourceEventId: number }
export interface HarnSessionRecapToolExchange {
  toolCallId: string
  toolName: string | null
  state: HarnSessionRecapToolState
  callObserved: boolean
  resultObserved: boolean
  input: ACPValue | null
  output: ACPValue | null
  verification: HarnSessionRecapVerificationFact | null
  sourceEventIds: number[]
}
export interface HarnSessionRecapPlanStep { id: string; content: string; status: HarnSessionRecapPlanStepStatus }
export interface HarnSessionRecapPlanEventFact { kind: HarnSessionRecapPlanEventKind; eventId: string; inputRevisionId: string | null }
export interface HarnSessionRecapPlanFact {
  documentId: string; revisionId: string; title: string; summary: string
  steps: HarnSessionRecapPlanStep[]; event: HarnSessionRecapPlanEventFact | null; sourceEventId: number
}
export interface HarnSessionRecapProgressEntry { content: string; status: HarnSessionRecapProgressStatus; priority: HarnSessionRecapProgressPriority | null }
export interface HarnSessionRecapProgressFact { message: string | null; entries: HarnSessionRecapProgressEntry[]; replace: boolean; sourceEventId: number }
export interface HarnSessionRecapTerminalFact {
  state: HarnSessionRecapCompletionState; finalStatus: string | null; stopReason: string | null
  kind: string | null; owner: string | null; reason: string | null; sourceEventId: number
}
export interface HarnSessionRecapIteration {
  iteration: number | null; state: HarnSessionRecapCompletionState
  assistantText: HarnSessionRecapTextFact[]; tools: HarnSessionRecapToolExchange[]
  plans: HarnSessionRecapPlanFact[]; progress: HarnSessionRecapProgressFact[]; sourceEventIds: number[]
}
export interface HarnSessionPromptTurnRecap {
  turnId: string; runId: string; state: HarnSessionRecapCompletionState
  prompts: HarnSessionRecapTextFact[]; iterations: HarnSessionRecapIteration[]
  terminal: HarnSessionRecapTerminalFact | null; sourceEventIds: number[]
}
export interface HarnSessionRecapSnapshot {
  schemaVersion: number; sessionId: string; query: HarnSessionRecapQuery
  cursor: HarnSessionRecapCursor; coverage: HarnSessionRecapCoverage; source: HarnSessionRecapSource
  contentHash: string; projectionHash: string; turns: HarnSessionPromptTurnRecap[]
  extensions: Record<string, ACPValue>
}
export type HarnSessionRecapAvailability =
  | { state: "available"; snapshot: HarnSessionRecapSnapshot }
  | { state: "unavailable"; reason: HarnSessionRecapUnavailableReason }

const HARN_SESSION_RECAP_KEYS = {
  snapshot: ["schemaVersion", "sessionId", "query", "cursor", "coverage", "source", "contentHash", "projectionHash", "turns", "extensions"],
  query: ["sessionId", "runId", "turnId", "fromEventId", "limit"],
  cursor: ["lastEventId", "nextEventId"],
  coverage: ["scanned", "matched", "pending", "unassigned", "truncated"],
  source: ["firstEventId", "lastEventId", "events"],
  sourceEvent: ["eventId", "recordHash"],
  text: ["text", "sourceEventId"],
  verification: ["schema", "status", "verifiedPaths", "sourceEventId"],
  tool: ["toolCallId", "toolName", "state", "callObserved", "resultObserved", "input", "output", "verification", "sourceEventIds"],
  planStep: ["id", "content", "status"],
  planEvent: ["kind", "eventId", "inputRevisionId"],
  plan: ["documentId", "revisionId", "title", "summary", "steps", "event", "sourceEventId"],
  progressEntry: ["content", "status", "priority"],
  progress: ["message", "entries", "replace", "sourceEventId"],
  terminal: ["state", "finalStatus", "stopReason", "kind", "owner", "reason", "sourceEventId"],
  iteration: ["iteration", "state", "assistantText", "tools", "plans", "progress", "sourceEventIds"],
  turn: ["turnId", "runId", "state", "prompts", "iterations", "terminal", "sourceEventIds"],
} as const

function harnSessionRecapObject(value: unknown, label: string, keys: readonly string[]): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new TypeError(`${label} must be an object`)
  }
  const object = value as Record<string, unknown>
  const known = new Set(keys)
  for (const key of Object.keys(object)) {
    if (!known.has(key)) throw new TypeError(`${label} contains unknown field ${key}`)
  }
  return object
}

function harnSessionRecapArray(value: unknown, label: string): unknown[] {
  if (!Array.isArray(value)) throw new TypeError(`${label} must be an array`)
  return value
}

function validateHarnSessionRecapSnapshot(value: unknown): void {
  const snapshot = harnSessionRecapObject(value, "Harn session recap snapshot", HARN_SESSION_RECAP_KEYS.snapshot)
  harnSessionRecapObject(snapshot.query, "Harn session recap query", HARN_SESSION_RECAP_KEYS.query)
  harnSessionRecapObject(snapshot.cursor, "Harn session recap cursor", HARN_SESSION_RECAP_KEYS.cursor)
  harnSessionRecapObject(snapshot.coverage, "Harn session recap coverage", HARN_SESSION_RECAP_KEYS.coverage)
  const source = harnSessionRecapObject(snapshot.source, "Harn session recap source", HARN_SESSION_RECAP_KEYS.source)
  for (const event of harnSessionRecapArray(source.events, "Harn session recap source events")) {
    harnSessionRecapObject(event, "Harn session recap source event", HARN_SESSION_RECAP_KEYS.sourceEvent)
  }
  for (const turnValue of harnSessionRecapArray(snapshot.turns, "Harn session recap turns")) {
    const turn = harnSessionRecapObject(turnValue, "Harn session recap turn", HARN_SESSION_RECAP_KEYS.turn)
    for (const prompt of harnSessionRecapArray(turn.prompts, "Harn session recap prompts")) {
      harnSessionRecapObject(prompt, "Harn session recap text", HARN_SESSION_RECAP_KEYS.text)
    }
    if (turn.terminal !== null) harnSessionRecapObject(turn.terminal, "Harn session recap terminal", HARN_SESSION_RECAP_KEYS.terminal)
    for (const iterationValue of harnSessionRecapArray(turn.iterations, "Harn session recap iterations")) {
      const iteration = harnSessionRecapObject(iterationValue, "Harn session recap iteration", HARN_SESSION_RECAP_KEYS.iteration)
      for (const text of harnSessionRecapArray(iteration.assistantText, "Harn session recap assistant text")) {
        harnSessionRecapObject(text, "Harn session recap text", HARN_SESSION_RECAP_KEYS.text)
      }
      for (const toolValue of harnSessionRecapArray(iteration.tools, "Harn session recap tools")) {
        const tool = harnSessionRecapObject(toolValue, "Harn session recap tool", HARN_SESSION_RECAP_KEYS.tool)
        if (tool.verification !== null) {
          const verification = harnSessionRecapObject(tool.verification, "Harn session recap verification", HARN_SESSION_RECAP_KEYS.verification)
          if (verification.status !== "passed") throw new TypeError("Harn session recap verification status must be passed")
        }
      }
      for (const planValue of harnSessionRecapArray(iteration.plans, "Harn session recap plans")) {
        const plan = harnSessionRecapObject(planValue, "Harn session recap plan", HARN_SESSION_RECAP_KEYS.plan)
        for (const step of harnSessionRecapArray(plan.steps, "Harn session recap plan steps")) {
          harnSessionRecapObject(step, "Harn session recap plan step", HARN_SESSION_RECAP_KEYS.planStep)
        }
        if (plan.event !== null) harnSessionRecapObject(plan.event, "Harn session recap plan event", HARN_SESSION_RECAP_KEYS.planEvent)
      }
      for (const progressValue of harnSessionRecapArray(iteration.progress, "Harn session recap progress")) {
        const progress = harnSessionRecapObject(progressValue, "Harn session recap progress", HARN_SESSION_RECAP_KEYS.progress)
        for (const entry of harnSessionRecapArray(progress.entries, "Harn session recap progress entries")) {
          harnSessionRecapObject(entry, "Harn session recap progress entry", HARN_SESSION_RECAP_KEYS.progressEntry)
        }
      }
    }
  }
}

/** Decode the closed recap envelope without silently dropping future fields. */
export function decodeHarnSessionRecapAvailability(value: unknown): HarnSessionRecapAvailability {
  const base = harnSessionRecapObject(value, "Harn session recap availability", ["state", "snapshot", "reason"])
  const availability = base as Record<string, unknown>
  if (availability.state === "unavailable") {
    harnSessionRecapObject(value, "Harn session recap availability", ["state", "reason"])
    return value as HarnSessionRecapAvailability
  }
  if (availability.state !== "available") {
    throw new TypeError("Harn session recap availability has an unknown state")
  }
  harnSessionRecapObject(value, "Harn session recap availability", ["state", "snapshot"])
  validateHarnSessionRecapSnapshot(availability.snapshot)
  return value as HarnSessionRecapAvailability
}
