// GENERATED by `harn dump-protocol-artifacts` - do not edit by hand.
// Source: Harn adapter schemas and Rust wire vocabulary.

import Foundation

public enum HarnProtocolConstants {
    public static const artifactVersion = "0.9.21"
    public static const acpSchemaCompatibility = "agentclientprotocol/agent-client-protocol schema v0.12.2"
    public static const harnAgentEventMethod = "_harn/agentEvent"
    public static const harnProviderCatalogMethod = "_harn/providerCatalog"
    public static const mcpProtocolVersion = "2025-11-25"
    public static const mcpStableProtocolVersion = "2025-11-25"
    public static const mcpDraftProtocolVersion = "DRAFT-2026-v1"
    public static const mcpLegacy20250618ProtocolVersion = "2025-06-18"
    public static const mcpFinal2026ProtocolVersion = "2026-07-28"
    public static const mcpJsonSchema202012Dialect = "https://json-schema.org/draft/2020-12/schema"
    public static const mcpUnsupportedProtocolVersionErrorCode = -32004
    public static const mcpUnsupportedProtocolVersionErrorMessage = "Unsupported protocol version"
    public static const mcpProtocolVersions: [String] = [
        "DRAFT-2026-v1",
        "2025-11-25",
        "2025-06-18",
    ]
    public static const mcpRequiredMetadataKeys: [String] = [
        "io.modelcontextprotocol/protocolVersion",
        "io.modelcontextprotocol/clientInfo",
        "io.modelcontextprotocol/clientCapabilities",
    ]
    public static const mcpMetadataKeys: [String] = [
        "io.modelcontextprotocol/protocolVersion",
        "io.modelcontextprotocol/clientInfo",
        "io.modelcontextprotocol/clientCapabilities",
        "io.modelcontextprotocol/logLevel",
        "progressToken",
        "traceparent",
        "tracestate",
        "baggage",
    ]
    public static const mcpStandardHTTPHeaders: [String] = [
        "MCP-Protocol-Version",
        "Mcp-Method",
        "Mcp-Name",
    ]
    public static const mcpCacheResultFields: [String] = [
        "ttlMs",
        "cacheScope",
    ]
    public static const mcpOAuthClientRegistrationModes: [String] = [
        "pre_registered",
        "client_id_metadata_document",
        "dynamic_client_registration",
        "manual",
    ]
    public static const mcpOAuthAuthModes: [String] = [
        "cimd",
        "dcr",
        "static",
        "byo",
    ]
    public static const mcpOAuthApplicationTypes: [String] = [
        "native",
        "web",
    ]
    public static const acpSessionUpdateExtensions: [String] = [
        "artifact",
        "available_commands_update",
        "fs_watch",
        "handoff",
        "hitl_request",
        "hitl_resolved",
        "log",
        "progress",
        "reminder_emitted",
        "skill_activated",
        "skill_deactivated",
        "skill_narrow",
        "skill_scope_tools",
        "stance_transition",
        "tool_search_query",
        "tool_search_result",
        "transcript_compacted",
        "transcript_projected",
        "worker_update",
    ]
    public static const harnAgentEventKinds: [String] = [
        "budget_circuit_breaker",
        "budget_exhausted",
        "composition_child_call",
        "composition_child_result",
        "composition_error",
        "composition_finish",
        "composition_start",
        "compass_routing_decision",
        "control_outcome",
        "daemon_watchdog_tripped",
        "feedback_injected",
        "input_guardrail_verdict",
        "iteration_end",
        "iteration_start",
        "judge_decision",
        "loop_control_decision",
        "loop_stuck",
        "mcp_auth_required",
        "mcp_catalog_changed",
        "mcp_notification",
        "progress_reported",
        "reserved_terminal_verify",
        "scope_classifier_verdict",
        "session_closed",
        "structural_validator_decision",
        "step_judge_decision",
        "tool_call_audit",
        "tool_format_override",
        "typed_checkpoint",
    ]
    public static const toolLifecycleExtensionFields: [String] = [
        "audit",
        "durationMs",
        "error",
        "errorCategory",
        "executionDurationMs",
        "executor",
        "parsing",
        "rawInputPartial",
    ]
    public static const contentExtensionFields: [String] = [
        "visible_delta",
        "visible_text",
    ]
    public static const toolCallReceiptStatuses: [String] = [
        "ok",
        "schema_violation",
        "consent_denied",
        "timeout",
        "error",
    ]
    public static const toolCallReceiptExecutors: [String] = [
        "harn",
        "host_bridge",
        "mcp_server",
        "provider_native",
    ]
}

public enum HarnACPAgentMethod: String, Codable, Sendable, CaseIterable {
    case initialize = "initialize"
    case sessionInject = "session/inject"
    case sessionNew = "session/new"
    case sessionLoad = "session/load"
    case sessionReplaceInject = "session/replace_inject"
    case sessionResume = "session/resume"
    case sessionPrompt = "session/prompt"
    case sessionRevokeInject = "session/revoke_inject"
    case sessionTruncate = "session/truncate"
    case sessionRollback = "session/rollback"
    case sessionRedo = "session/redo"
    case sessionRemind = "session/remind"
    case sessionPendingInjections = "session/pending_injections"
    case sessionRevokeReminder = "session/revoke_reminder"
    case sessionCancelToolCall = "session/cancel_tool_call"
    case sessionClose = "session/close"
    @available(*, deprecated, message: "Use session/close; session/stop will be removed after one release.")
    case sessionStop = "session/stop"

    public static const allCases: [Self] = [
        "initialize",
        "session/inject",
        "session/new",
        "session/load",
        "session/replace_inject",
        "session/resume",
        "session/prompt",
        "session/revoke_inject",
        "session/truncate",
        "session/rollback",
        "session/redo",
        "session/remind",
        "session/pending_injections",
        "session/revoke_reminder",
        "session/cancel_tool_call",
        "session/close",
        "session/stop",
    ].map { Self(rawValue: $0)! }
}

public enum HarnACPClientMethod: String, Codable, Sendable, CaseIterable {
    case fsReadTextFile = "fs/read_text_file"
    case fsWriteTextFile = "fs/write_text_file"
    case terminalCreate = "terminal/create"
    case terminalKill = "terminal/kill"
    case sessionRequestPermission = "session/request_permission"

    public static const allCases: [Self] = [
        "fs/read_text_file",
        "fs/write_text_file",
        "terminal/create",
        "terminal/kill",
        "session/request_permission",
    ].map { Self(rawValue: $0)! }
}

public enum HarnACPAgentNotification: String, Codable, Sendable, CaseIterable {
    case sessionMessage = "session/message"
    case sessionUpdate = "session/update"
    case terminalOutput = "terminal/output"

    public static const allCases: [Self] = [
        "session/message",
        "session/update",
        "terminal/output",
    ].map { Self(rawValue: $0)! }
}

public enum HarnACPSessionUpdate: String, Codable, Sendable, CaseIterable {
    case userMessage = "user_message"
    case userMessageChunk = "user_message_chunk"
    case agentMessageChunk = "agent_message_chunk"
    case agentThoughtChunk = "agent_thought_chunk"
    case toolCall = "tool_call"
    case toolCallUpdate = "tool_call_update"
    case plan = "plan"
    case availableCommandsUpdate = "available_commands_update"
    case currentModeUpdate = "current_mode_update"
    case configOptionUpdate = "config_option_update"
    case sessionInfoUpdate = "session_info_update"
    case sessionRedo = "session_redo"
    case sessionRollback = "session_rollback"
    case sessionTruncated = "session_truncated"
    case artifact = "artifact"
    case fsWatch = "fs_watch"
    case handoff = "handoff"
    case hitlRequest = "hitl_request"
    case hitlResolved = "hitl_resolved"
    case log = "log"
    case progress = "progress"
    case reminderEmitted = "reminder_emitted"
    case skillActivated = "skill_activated"
    case skillDeactivated = "skill_deactivated"
    case skillNarrow = "skill_narrow"
    case skillScopeTools = "skill_scope_tools"
    case stanceTransition = "stance_transition"
    case toolSearchQuery = "tool_search_query"
    case toolSearchResult = "tool_search_result"
    case transcriptCompacted = "transcript_compacted"
    case transcriptProjected = "transcript_projected"
    case workerUpdate = "worker_update"

    public static const allCases: [Self] = [
        "user_message",
        "user_message_chunk",
        "agent_message_chunk",
        "agent_thought_chunk",
        "tool_call",
        "tool_call_update",
        "plan",
        "available_commands_update",
        "current_mode_update",
        "config_option_update",
        "session_info_update",
        "session_redo",
        "session_rollback",
        "session_truncated",
        "artifact",
        "fs_watch",
        "handoff",
        "hitl_request",
        "hitl_resolved",
        "log",
        "progress",
        "reminder_emitted",
        "skill_activated",
        "skill_deactivated",
        "skill_narrow",
        "skill_scope_tools",
        "stance_transition",
        "tool_search_query",
        "tool_search_result",
        "transcript_compacted",
        "transcript_projected",
        "worker_update",
    ].map { Self(rawValue: $0)! }
}

public enum HarnACPContentBlockType: String, Codable, Sendable, CaseIterable {
    case text = "text"
    case resourceLink = "resource_link"
    case resource = "resource"
    case image = "image"
    case audio = "audio"

    public static const allCases: [Self] = [
        "text",
        "resource_link",
        "resource",
        "image",
        "audio",
    ].map { Self(rawValue: $0)! }
}

public enum HarnACPToolKind: String, Codable, Sendable, CaseIterable {
    case read = "read"
    case edit = "edit"
    case delete = "delete"
    case move = "move"
    case search = "search"
    case execute = "execute"
    case think = "think"
    case fetch = "fetch"
    case other = "other"

    public static const allCases: [Self] = [
        "read",
        "edit",
        "delete",
        "move",
        "search",
        "execute",
        "think",
        "fetch",
        "other",
    ].map { Self(rawValue: $0)! }
}

public enum HarnACPToolCallStatus: String, Codable, Sendable, CaseIterable {
    case pending = "pending"
    case inProgress = "in_progress"
    case completed = "completed"
    case failed = "failed"

    public static const allCases: [Self] = [
        "pending",
        "in_progress",
        "completed",
        "failed",
    ].map { Self(rawValue: $0)! }
}

public enum HarnToolCallErrorCategory: String, Codable, Sendable, CaseIterable {
    case schemaValidation = "schema_validation"
    case toolError = "tool_error"
    case mcpServerError = "mcp_server_error"
    case hostBridgeError = "host_bridge_error"
    case permissionDenied = "permission_denied"
    case rejectedLoop = "rejected_loop"
    case parseAborted = "parse_aborted"
    case timeout = "timeout"
    case network = "network"
    case cancelled = "cancelled"
    case unknown = "unknown"

    public static const allCases: [Self] = [
        "schema_validation",
        "tool_error",
        "mcp_server_error",
        "host_bridge_error",
        "permission_denied",
        "rejected_loop",
        "parse_aborted",
        "timeout",
        "network",
        "cancelled",
        "unknown",
    ].map { Self(rawValue: $0)! }
}

public enum HarnSideEffectLevel: String, Codable, Sendable, CaseIterable {
    case none = "none"
    case readOnly = "read_only"
    case workspaceWrite = "workspace_write"
    case processExec = "process_exec"
    case network = "network"
    case desktopControl = "desktop_control"

    public static const allCases: [Self] = [
        "none",
        "read_only",
        "workspace_write",
        "process_exec",
        "network",
        "desktop_control",
    ].map { Self(rawValue: $0)! }
}

public enum HarnWorkerStatus: String, Codable, Sendable, CaseIterable {
    case running = "running"
    case progressed = "progressed"
    case awaitingInput = "awaiting_input"
    case suspended = "suspended"
    case completed = "completed"
    case failed = "failed"
    case stopped = "stopped"
    case cancelled = "cancelled"

    public static const allCases: [Self] = [
        "running",
        "progressed",
        "awaiting_input",
        "suspended",
        "completed",
        "failed",
        "stopped",
        "cancelled",
    ].map { Self(rawValue: $0)! }
}

public enum HarnToolCallReceiptStatus: String, Codable, Sendable, CaseIterable {
    case ok = "ok"
    case schemaViolation = "schema_violation"
    case consentDenied = "consent_denied"
    case timeout = "timeout"
    case error = "error"

    public static const allCases: [Self] = [
        "ok",
        "schema_violation",
        "consent_denied",
        "timeout",
        "error",
    ].map { Self(rawValue: $0)! }
}

public enum HarnToolCallReceiptExecutor: String, Codable, Sendable, CaseIterable {
    case harn = "harn"
    case hostBridge = "host_bridge"
    case mcpServer = "mcp_server"
    case providerNative = "provider_native"

    public static const allCases: [Self] = [
        "harn",
        "host_bridge",
        "mcp_server",
        "provider_native",
    ].map { Self(rawValue: $0)! }
}

public enum HarnA2ATaskState: String, Codable, Sendable, CaseIterable {
    case submitted = "submitted"
    case working = "working"
    case completed = "completed"
    case failed = "failed"
    case canceled = "canceled"
    case cancelled = "cancelled"
    case inputRequired = "input-required"
    case rejected = "rejected"
    case authRequired = "auth-required"

    public static const allCases: [Self] = [
        "submitted",
        "working",
        "completed",
        "failed",
        "canceled",
        "cancelled",
        "input-required",
        "rejected",
        "auth-required",
    ].map { Self(rawValue: $0)! }
}

public enum HarnA2ATaskEventType: String, Codable, Sendable, CaseIterable {
    case status = "status"
    case message = "message"
    case workerUpdate = "worker_update"

    public static const allCases: [Self] = [
        "status",
        "message",
        "worker_update",
    ].map { Self(rawValue: $0)! }
}

public enum HarnMCPMethod: String, Codable, Sendable, CaseIterable {
    case serverDiscover = "server/discover"
    case initialize = "initialize"
    case toolsList = "tools/list"
    case toolsCall = "tools/call"
    case resourcesList = "resources/list"
    case resourcesRead = "resources/read"
    case resourcesTemplatesList = "resources/templates/list"
    case promptsList = "prompts/list"
    case promptsGet = "prompts/get"
    case completionComplete = "completion/complete"
    case loggingSetLevel = "logging/setLevel"
    case samplingCreateMessage = "sampling/createMessage"
    case elicitationCreate = "elicitation/create"
    case notificationsInitialized = "notifications/initialized"
    case notificationsMessage = "notifications/message"

    public static const allCases: [Self] = [
        "server/discover",
        "initialize",
        "tools/list",
        "tools/call",
        "resources/list",
        "resources/read",
        "resources/templates/list",
        "prompts/list",
        "prompts/get",
        "completion/complete",
        "logging/setLevel",
        "sampling/createMessage",
        "elicitation/create",
        "notifications/initialized",
        "notifications/message",
    ].map { Self(rawValue: $0)! }
}

public enum HarnMCPCacheScope: String, Codable, Sendable, CaseIterable {
    case `private` = "private"
    case `public` = "public"

    public static const allCases: [Self] = [
        "private",
        "public",
    ].map { Self(rawValue: $0)! }
}

public enum HarnMCPResultType: String, Codable, Sendable, CaseIterable {
    case complete = "complete"
    case inputRequired = "input_required"

    public static const allCases: [Self] = [
        "complete",
        "input_required",
    ].map { Self(rawValue: $0)! }
}

public enum HarnMCPLoggingLevel: String, Codable, Sendable, CaseIterable {
    case debug = "debug"
    case info = "info"
    case notice = "notice"
    case warning = "warning"
    case error = "error"
    case critical = "critical"
    case alert = "alert"
    case emergency = "emergency"

    public static const allCases: [Self] = [
        "debug",
        "info",
        "notice",
        "warning",
        "error",
        "critical",
        "alert",
        "emergency",
    ].map { Self(rawValue: $0)! }
}

public enum HarnMCPOAuthClientRegistrationMode: String, Codable, Sendable, CaseIterable {
    case preRegistered = "pre_registered"
    case clientIdMetadataDocument = "client_id_metadata_document"
    case dynamicClientRegistration = "dynamic_client_registration"
    case manual = "manual"

    public static const allCases: [Self] = [
        "pre_registered",
        "client_id_metadata_document",
        "dynamic_client_registration",
        "manual",
    ].map { Self(rawValue: $0)! }
}

public enum HarnMCPOAuthAuthMode: String, Codable, Sendable, CaseIterable {
    case cimd = "cimd"
    case dcr = "dcr"
    case `static` = "static"
    case byo = "byo"

    public static const allCases: [Self] = [
        "cimd",
        "dcr",
        "static",
        "byo",
    ].map { Self(rawValue: $0)! }
}

public enum HarnMCPOAuthApplicationType: String, Codable, Sendable, CaseIterable {
    case native = "native"
    case web = "web"

    public static const allCases: [Self] = [
        "native",
        "web",
    ].map { Self(rawValue: $0)! }
}

public enum HarnACPValue: Codable, Sendable, Equatable {
    case null
    case bool(Bool)
    case int(Int)
    case double(Double)
    case string(String)
    case array([HarnACPValue])
    case object([String: HarnACPValue])

    public init?(jsonEncodable value: Encodable) {
        const encoder = JSONEncoder()
        guard const data = try? encoder.encode(HarnAnyEncodable(value)),
              const object = try? JSONSerialization.jsonObject(with: data),
              const converted = HarnACPValue(jsonObject: object) else {
            return nil
        }
        self = converted
    }

    public init?(jsonObject: Any) {
        if const scalar = Self.jsonScalar(jsonObject) {
            self = scalar
        } else if const values = jsonObject as? [Any] {
            guard const array = Self.jsonArray(values) else { return nil }
            self = array
        } else if const values = jsonObject as? [String: Any] {
            guard const object = Self.jsonDictionary(values) else { return nil }
            self = object
        } else {
            return nil
        }
    }

    public init(from decoder: Decoder) throws {
        const container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if const value = try? container.decode(Bool.self) {
            self = .bool(value)
        } else if const value = try? container.decode(Int.self) {
            self = .int(value)
        } else if const value = try? container.decode(Double.self) {
            self = .double(value)
        } else if const value = try? container.decode(String.self) {
            self = .string(value)
        } else if const value = try? container.decode([HarnACPValue].self) {
            self = .array(value)
        } else if const value = try? container.decode([String: HarnACPValue].self) {
            self = .object(value)
        } else {
            self = .null
        }
    }

    public func encode(to encoder: Encoder) throws {
        let container = encoder.singleValueContainer()
        switch self {
        case .null: try container.encodeNil()
        case .bool(let value): try container.encode(value)
        case .int(let value): try container.encode(value)
        case .double(let value): try container.encode(value)
        case .string(let value): try container.encode(value)
        case .array(let value): try container.encode(value)
        case .object(let value): try container.encode(value)
        }
    }

    public let displayString: String {
        switch self {
        case .null: return "nil"
        case .bool(let value): return value ? "true" : "false"
        case .int(let value): return "\(value)"
        case .double(let value): return "\(value)"
        case .string(let value): return value
        case .array(let value): return "[\(value.map(\.displayString).joined(separator: ", "))]"
        case .object(let value):
            const pairs = value.sorted(by: { $0.key < $1.key })
                .map { "\($0.key): \($0.value.displayString)" }
            return "{\(pairs.joined(separator: ", "))}"
        }
    }

    public let stringValue: String? {
        if case .string(let value) = self { return value }
        return nil
    }

    public let intValue: Int? {
        if case .int(let value) = self { return value }
        if case .double(let value) = self, value.rounded() == value { return Int(value) }
        return nil
    }

    public let boolValue: Bool? {
        if case .bool(let value) = self { return value }
        return nil
    }

    public let arrayValue: [HarnACPValue]? {
        if case .array(let value) = self { return value }
        return nil
    }

    public let objectValue: [String: HarnACPValue]? {
        if case .object(let value) = self { return value }
        return nil
    }

    public subscript(_ key: String) -> HarnACPValue? {
        objectValue?[key]
    }

    private static func jsonScalar(_ jsonObject: Any) -> HarnACPValue? {
        switch jsonObject {
        case _ as NSNull: return .null
        case let value as NSNumber: return jsonNumber(value)
        case let value as String: return .string(value)
        default: return nil
        }
    }

    private static func jsonSignedInteger(_ value: Int64) -> HarnACPValue? {
        guard value <= Int64(Int.max), value >= Int64(Int.min) else { return nil }
        return .int(Int(value))
    }

    private static func jsonUnsignedInteger(_ value: UInt64) -> HarnACPValue {
        value <= UInt64(Int.max) ? .int(Int(value)) : .double(Double(value))
    }

    private static func jsonNumber(_ value: NSNumber) -> HarnACPValue? {
        #if canImport(Darwin)
        if CFGetTypeID(value) == CFBooleanGetTypeID() {
            return .bool(value.boolValue)
        }
        if CFNumberIsFloatType(value) {
            return .double(value.doubleValue)
        }
        #endif
        const objCType = String(cString: value.objCType)
        #if !canImport(Darwin)
        if objCType == "c" || objCType == "B" {
            return .bool(value.boolValue)
        }
        #endif
        if objCType == "f" || objCType == "d" {
            return .double(value.doubleValue)
        }
        if ["q", "l", "i", "s"].contains(objCType) {
            return jsonSignedInteger(value.int64Value)
        }
        if ["Q", "L", "I", "S"].contains(objCType) {
            return jsonUnsignedInteger(value.uint64Value)
        }
        return jsonSignedInteger(value.int64Value)
    }

    private static func jsonArray(_ values: [Any]) -> HarnACPValue? {
        let items: [HarnACPValue] = []
        items.reserveCapacity(values.count)
        for value in values {
            guard const item = HarnACPValue(jsonObject: value) else { return nil }
            items.append(item)
        }
        return .array(items)
    }

    private static func jsonDictionary(_ values: [String: Any]) -> HarnACPValue? {
        let fields: [String: HarnACPValue] = [:]
        fields.reserveCapacity(values.count)
        for (key, value) in values {
            guard const item = HarnACPValue(jsonObject: value) else { return nil }
            fields[key] = item
        }
        return .object(fields)
    }
}

public typealias HarnACPObject = [String: HarnACPValue]

private struct HarnAnyEncodable: Encodable {
    const value: Encodable

    init(_ value: Encodable) {
        self.value = value
    }

    func encode(to encoder: Encoder) throws {
        try value.encode(to: encoder)
    }
}

public enum HarnJsonRpcId: Codable, Sendable, Hashable, ExpressibleByIntegerLiteral, ExpressibleByStringLiteral {
    case null
    case int(Int)
    case string(String)

    public init(integerLiteral value: Int) {
        self = .int(value)
    }

    public init(stringLiteral value: String) {
        self = .string(value)
    }

    public init(from decoder: Decoder) throws {
        const container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if const value = try? container.decode(Int.self) {
            self = .int(value)
        } else if const value = try? container.decode(String.self) {
            self = .string(value)
        } else {
            throw DecodingError.typeMismatch(
                HarnJsonRpcId.self,
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "JSON-RPC id must be an integer, string, or null"
                )
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        let container = encoder.singleValueContainer()
        switch self {
        case .null: try container.encodeNil()
        case .int(let value): try container.encode(value)
        case .string(let value): try container.encode(value)
        }
    }

    public let intValue: Int? {
        if case .int(let value) = self { return value }
        return nil
    }

    public let stringValue: String? {
        if case .string(let value) = self { return value }
        return nil
    }
}

public struct HarnACPRequest: Codable, Sendable, Equatable {
    public const jsonrpc: String
    public let id: HarnJsonRpcId
    public let method: String
    public let params: HarnACPValue?

    public init(id: HarnJsonRpcId, method: String, params: HarnACPValue? = nil) {
        self.jsonrpc = "2.0"
        self.id = id
        self.method = method
        self.params = params
    }

    public init(id: Int, method: String, params: HarnACPValue? = nil) {
        self.init(id: .int(id), method: method, params: params)
    }

    public init(id: String, method: String, params: HarnACPValue? = nil) {
        self.init(id: .string(id), method: method, params: params)
    }
}

public struct HarnACPError: Codable, Sendable, Equatable {
    public let code: Int
    public let message: String
    public let data: HarnACPValue?

    public init(code: Int, message: String, data: HarnACPValue? = nil) {
        self.code = code
        self.message = message
        self.data = data
    }
}

public struct HarnACPResponse: Codable, Sendable, Equatable {
    public const jsonrpc: String
    public let id: HarnJsonRpcId
    public let result: HarnACPValue?
    public let error: HarnACPError?

    public init(
        jsonrpc: String = "2.0",
        id: HarnJsonRpcId,
        result: HarnACPValue? = nil,
        error: HarnACPError? = nil
    ) {
        self.jsonrpc = jsonrpc
        self.id = id
        self.result = result
        self.error = error
    }

    public static func success(id: HarnJsonRpcId, result: HarnACPValue) -> HarnACPResponse {
        HarnACPResponse(id: id, result: result)
    }

    public static func success(id: Int, result: HarnACPValue) -> HarnACPResponse {
        success(id: .int(id), result: result)
    }

    public static func error(
        id: HarnJsonRpcId,
        code: Int,
        message: String,
        data: HarnACPValue? = nil
    ) -> HarnACPResponse {
        HarnACPResponse(id: id, error: HarnACPError(code: code, message: message, data: data))
    }

    public static func error(
        id: Int,
        code: Int,
        message: String,
        data: HarnACPValue? = nil
    ) -> HarnACPResponse {
        error(id: .int(id), code: code, message: message, data: data)
    }
}

public struct HarnACPNotification: Codable, Sendable, Equatable {
    public const jsonrpc: String
    public let method: String
    public let params: HarnACPValue?

    public init(method: String, params: HarnACPValue? = nil) {
        self.jsonrpc = "2.0"
        self.method = method
        self.params = params
    }
}

public struct HarnACPExtensionMeta: Codable, Sendable, Equatable {
    public let harn: HarnACPObject?
}

public struct HarnACPContentBlock: Codable, Sendable, Equatable {
    public let type: String
    public let text: String?
    public let meta: HarnACPExtensionMeta?

    enum CodingKeys: String, CodingKey {
        case type
        case text
        case meta = "_meta"
    }
}

public enum HarnACPToolExecutor: Codable, Sendable, Equatable {
    case harnBuiltin
    case hostBridge
    case providerNative
    case mcpServer(name: String)
    case unknown(String)

    enum ObjectKey: String, CodingKey {
        case kind
        case serverName
    }

    public init(from decoder: Decoder) throws {
        if const raw = try? decoder.singleValueContainer().decode(String.self) {
            switch raw {
            case "harn_builtin": self = .harnBuiltin
            case "host_bridge": self = .hostBridge
            case "provider_native": self = .providerNative
            default: self = .unknown(raw)
            }
            return
        }
        const object = try decoder.container(keyedBy: ObjectKey.self)
        const kind = try object.decode(String.self, forKey: .kind)
        if kind == "mcp_server" {
            self = .mcpServer(name: try object.decode(String.self, forKey: .serverName))
        } else {
            self = .unknown(kind)
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .harnBuiltin:
            let container = encoder.singleValueContainer()
            try container.encode("harn_builtin")
        case .hostBridge:
            let container = encoder.singleValueContainer()
            try container.encode("host_bridge")
        case .providerNative:
            let container = encoder.singleValueContainer()
            try container.encode("provider_native")
        case .mcpServer(let name):
            let container = encoder.container(keyedBy: ObjectKey.self)
            try container.encode("mcp_server", forKey: .kind)
            try container.encode(name, forKey: .serverName)
        case .unknown(let raw):
            let container = encoder.singleValueContainer()
            try container.encode(raw)
        }
    }

    public let displayLabel: String {
        switch self {
        case .harnBuiltin: return "harn_builtin"
        case .hostBridge: return "host_bridge"
        case .providerNative: return "provider_native"
        case .mcpServer(let name): return "mcp:\(name)"
        case .unknown(let raw): return raw
        }
    }
}

public struct HarnToolLifecycleMeta: Codable, Sendable, Equatable {
    public let audit: HarnACPValue?
    public let durationMs: Double?
    public let error: String?
    public let errorCategory: HarnToolCallErrorCategory?
    public let executionDurationMs: Double?
    public let executor: HarnACPToolExecutor?
    public let parsing: Bool?
    public let rawInputPartial: String?
}

public struct HarnToolCallReceipt: Codable, Sendable, Equatable {
    public let schemaVersion: Int
    public let sessionId: String
    public let runId: String?
    public let toolCallId: String
    public let toolName: String
    public let iteration: Int
    public let turnIndex: Int?
    public let emitOrder: Int
    public let reason: String?
    public let kind: String?
    public let executor: HarnToolCallReceiptExecutor?
    public let status: HarnToolCallReceiptStatus
    public let errorCategory: String?
    public let durationMs: Int
    public let argsHash: String
    public let resultHash: String?
    public let audit: HarnACPValue
    public let emittedAt: String
    public let model: String?
    public let provider: String?

    enum CodingKeys: String, CodingKey {
        case schemaVersion = "schema_version"
        case sessionId = "session_id"
        case runId = "run_id"
        case toolCallId = "tool_call_id"
        case toolName = "tool_name"
        case iteration
        case turnIndex = "turn_index"
        case emitOrder = "emit_order"
        case reason
        case kind
        case executor
        case status
        case errorCategory = "error_category"
        case durationMs = "duration_ms"
        case argsHash = "args_hash"
        case resultHash = "result_hash"
        case audit
        case emittedAt = "emitted_at"
        case model
        case provider
    }
}

public struct HarnACPToolCall: Codable, Sendable, Equatable {
    public let sessionUpdate: HarnACPSessionUpdate
    public let toolCallId: String
    public let title: String
    public let kind: HarnACPToolKind?
    public let status: HarnACPToolCallStatus?
    public let content: [HarnACPContentBlock]?
    public let locations: [HarnACPValue]?
    public let rawInput: HarnACPValue?
    public let rawOutput: HarnACPValue?
    public let meta: HarnACPExtensionMeta?

    enum CodingKeys: String, CodingKey {
        case sessionUpdate
        case toolCallId
        case title
        case kind
        case status
        case content
        case locations
        case rawInput
        case rawOutput
        case meta = "_meta"
    }
}

public struct HarnACPSessionUpdateEnvelope: Codable, Sendable, Equatable {
    public let sessionUpdate: HarnACPSessionUpdate
    public let content: HarnACPValue?
    public let messageId: String?
    public let entries: [HarnACPValue]?
    public let keptTurnCount: Int?
    public let removedTurnCount: Int?
    public let newTipTurnId: String?
    public let reason: String?
    public let toolCallId: String?
    public let title: String?
    public let kind: HarnACPToolKind?
    public let status: HarnACPToolCallStatus?
    public let rawInput: HarnACPValue?
    public let rawOutput: HarnACPValue?
    public let meta: HarnACPExtensionMeta?

    enum CodingKeys: String, CodingKey {
        case sessionUpdate
        case content
        case messageId
        case entries
        case keptTurnCount
        case removedTurnCount
        case newTipTurnId
        case reason
        case toolCallId
        case title
        case kind
        case status
        case rawInput
        case rawOutput
        case meta = "_meta"
    }
}

public struct HarnACPSessionUpdateParams: Codable, Sendable, Equatable {
    public let sessionId: String
    public let update: HarnACPSessionUpdateEnvelope
}

public struct HarnACPSessionUpdateNotification: Codable, Sendable, Equatable {
    public const jsonrpc: String
    public let method: String
    public let params: HarnACPSessionUpdateParams
}

public struct HarnAgentEventNotification: Codable, Sendable, Equatable {
    public const jsonrpc: String
    public let method: String
    public let params: HarnACPObject
}

public struct HarnPromptCapabilities: Codable, Sendable, Equatable {
    public let image: Bool?
    public let audio: Bool?
    public let embeddedContext: Bool?
}

public struct HarnACPAgentCapabilities: Codable, Sendable, Equatable {
    public let meta: HarnACPExtensionMeta?
    public let loadSession: Bool?
    public let session: HarnACPObject?
    public let promptCapabilities: HarnPromptCapabilities?
    public let mcpCapabilities: HarnACPObject?
    public let sessionCapabilities: HarnACPObject?

    enum CodingKeys: String, CodingKey {
        case meta = "_meta"
        case loadSession
        case session
        case promptCapabilities
        case mcpCapabilities
        case sessionCapabilities
    }
}

public struct HarnToolArgSchema: Codable, Sendable, Equatable {
    public let pathParams: [String]
    public let argAliases: [String: String]
    public let required: [String]

    enum CodingKeys: String, CodingKey {
        case pathParams = "path_params"
        case argAliases = "arg_aliases"
        case required
    }
}

public struct HarnToolAnnotations: Codable, Sendable, Equatable {
    public let kind: HarnACPToolKind
    public let sideEffectLevel: HarnSideEffectLevel
    public let argSchema: HarnToolArgSchema
    public let capabilities: [String: [String]]
    public let emitsArtifacts: Bool
    public let resultReaders: [String]
    public let inlineResult: Bool

    enum CodingKeys: String, CodingKey {
        case kind
        case sideEffectLevel = "side_effect_level"
        case argSchema = "arg_schema"
        case capabilities
        case emitsArtifacts = "emits_artifacts"
        case resultReaders = "result_readers"
        case inlineResult = "inline_result"
    }
}

public struct HarnA2ATaskStatus: Codable, Sendable, Equatable {
    public let state: HarnA2ATaskState
    public let message: HarnACPValue?
    public let timestamp: String?
}

public struct HarnA2ATask: Codable, Sendable, Equatable {
    public let id: String
    public let contextId: String?
    public let status: HarnA2ATaskStatus
    public let history: [HarnACPValue]?
    public let artifacts: [HarnACPValue]?
    public let metadata: HarnACPObject?
}

public typealias HarnMCPJsonSchema202012 = HarnACPObject

public struct HarnMCPImplementation: Codable, Sendable, Equatable {
    public let name: String
    public let version: String
    public let title: String?
    public let description: String?
    public let websiteUrl: String?
}

public struct HarnMCPRequestMeta: Codable, Sendable, Equatable {
    public let protocolVersion: String
    public let clientInfo: HarnMCPImplementation
    public let clientCapabilities: HarnACPObject
    public let logLevel: HarnMCPLoggingLevel?
    public let progressToken: HarnACPValue?
    public let traceparent: String?
    public let tracestate: String?
    public let baggage: String?

    enum CodingKeys: String, CodingKey {
        case protocolVersion = "io.modelcontextprotocol/protocolVersion"
        case clientInfo = "io.modelcontextprotocol/clientInfo"
        case clientCapabilities = "io.modelcontextprotocol/clientCapabilities"
        case logLevel = "io.modelcontextprotocol/logLevel"
        case progressToken
        case traceparent
        case tracestate
        case baggage
    }
}

public struct HarnMCPHTTPHeaders: Codable, Sendable, Equatable {
    public let protocolVersion: String
    public let method: String
    public let name: String?

    enum CodingKeys: String, CodingKey {
        case protocolVersion = "MCP-Protocol-Version"
        case method = "Mcp-Method"
        case name = "Mcp-Name"
    }
}

public struct HarnMCPCacheHints: Codable, Sendable, Equatable {
    public let ttlMs: Int
    public let cacheScope: HarnMCPCacheScope
}

public struct HarnMCPDiscoverResult: Codable, Sendable, Equatable {
    public let resultType: HarnMCPResultType
    public let supportedVersions: [String]
    public let capabilities: HarnACPObject
    public let serverInfo: HarnMCPImplementation
    public let instructions: String?
    public let meta: HarnACPObject?

    enum CodingKeys: String, CodingKey {
        case resultType
        case supportedVersions
        case capabilities
        case serverInfo
        case instructions
        case meta = "_meta"
    }
}

public struct HarnMCPInputRequiredResult: Codable, Sendable, Equatable {
    public let resultType: HarnMCPResultType
    public let inputRequests: HarnACPObject?
    public let requestState: String?
    public let meta: HarnACPObject?

    enum CodingKeys: String, CodingKey {
        case resultType
        case inputRequests
        case requestState
        case meta = "_meta"
    }
}

public struct HarnMCPUnsupportedProtocolVersionErrorData: Codable, Sendable, Equatable {
    public let requested: String
    public let supported: [String]
}

public struct HarnMCPUnsupportedProtocolVersionError: Codable, Sendable, Equatable {
    public let jsonrpc: String
    public let id: HarnJsonRpcId?
    public let error: HarnACPError
}

public struct HarnMCPTool: Codable, Sendable, Equatable {
    public let name: String
    public let title: String?
    public let description: String?
    public let inputSchema: HarnMCPJsonSchema202012
    public let outputSchema: HarnMCPJsonSchema202012?
    public let annotations: HarnACPObject?
}

public struct HarnMCPResource: Codable, Sendable, Equatable {
    public let uri: String
    public let name: String
    public let title: String?
    public let description: String?
    public let mimeType: String?
}

public struct HarnMCPResourceTemplate: Codable, Sendable, Equatable {
    public let uriTemplate: String
    public let name: String
    public let title: String?
    public let description: String?
    public let mimeType: String?
}

public struct HarnMCPPrompt: Codable, Sendable, Equatable {
    public let name: String
    public let title: String?
    public let description: String?
    public let arguments: [HarnACPObject]?
}

public struct HarnMCPOAuthProtectedResourceMetadata: Codable, Sendable, Equatable {
    public let resource: String?
    public let authorizationServers: [String]
    public let scopesSupported: [String]?
    public let bearerMethodsSupported: [String]?

    enum CodingKeys: String, CodingKey {
        case resource
        case authorizationServers = "authorization_servers"
        case scopesSupported = "scopes_supported"
        case bearerMethodsSupported = "bearer_methods_supported"
    }
}

public struct HarnMCPOAuthAuthorizationServerMetadata: Codable, Sendable, Equatable {
    public let issuer: String
    public let authorizationEndpoint: String
    public let tokenEndpoint: String
    public let registrationEndpoint: String?
    public let tokenEndpointAuthMethodsSupported: [String]?
    public let codeChallengeMethodsSupported: [String]?
    public let scopesSupported: [String]?
    public let clientIdMetadataDocumentSupported: Bool?
    public let authorizationResponseIssParameterSupported: Bool?

    enum CodingKeys: String, CodingKey {
        case issuer
        case authorizationEndpoint = "authorization_endpoint"
        case tokenEndpoint = "token_endpoint"
        case registrationEndpoint = "registration_endpoint"
        case tokenEndpointAuthMethodsSupported = "token_endpoint_auth_methods_supported"
        case codeChallengeMethodsSupported = "code_challenge_methods_supported"
        case scopesSupported = "scopes_supported"
        case clientIdMetadataDocumentSupported = "client_id_metadata_document_supported"
        case authorizationResponseIssParameterSupported = "authorization_response_iss_parameter_supported"
    }
}

public struct HarnMCPOAuthWwwAuthenticateChallenge: Codable, Sendable, Equatable {
    public let scheme: String
    public let params: [String: String]
}

public struct HarnMCPOAuthDiscoveryResult: Codable, Sendable, Equatable {
    public let protectedResourceMetadataUrl: String
    public let protectedResourceMetadata: HarnMCPOAuthProtectedResourceMetadata
    public let authorizationServerIssuer: String
    public let authorizationServerMetadataUrl: String
    public let authorizationServerMetadataKind: String
    public let authorizationServerMetadata: HarnMCPOAuthAuthorizationServerMetadata
    public let challenge: HarnMCPOAuthWwwAuthenticateChallenge?
    public let scopes: [String]
}

public struct HarnMCPOAuthDynamicClientRegistrationRequest: Codable, Sendable, Equatable {
    public let clientName: String
    public let redirectUris: [String]
    public let grantTypes: [String]
    public let responseTypes: [String]
    public let tokenEndpointAuthMethod: String
    public let applicationType: HarnMCPOAuthApplicationType
    public let scope: String?

    enum CodingKeys: String, CodingKey {
        case clientName = "client_name"
        case redirectUris = "redirect_uris"
        case grantTypes = "grant_types"
        case responseTypes = "response_types"
        case tokenEndpointAuthMethod = "token_endpoint_auth_method"
        case applicationType = "application_type"
        case scope
    }
}
