[package]
name = "harn-ir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "CFG and invariant analysis for the Harn programming language"

[dependencies]
harn-glob = { path = "../harn-glob", version = "=0.10.26", default-features = false }
harn-lexer = { path = "../harn-lexer", version = "=0.10.26" }
harn-parser = { path = "../harn-parser", version = "=0.10.26" }

[lints]
workspace = true
