module.exports = [
  "pipeline",
  "extends",
  "override",
  "let",
  "var",
  "if",
  "else",
  "for",
  "in",
  "match",
  "retry",
  "parallel",
  "defer",
  "return",
  "import",
  "true",
  "false",
  "nil",
  "try",
  "catch",
  "throw",
  "finally",
  "fn",
  "spawn",
  "while",
  "type",
  "enum",
  "eval_pack",
  "struct",
  "interface",
  "pub",
  "from",
  "to",
  "tool",
  "skill",
  "exclusive",
  "guard",
  "require",
  "deadline",
  "yield",
  "emit",
  "mutex",
  "break",
  "continue",
  "select",
  "impl",
  // First-class HITL primitives parsed as reserved keywords by the
  // runtime parser; surfaced here so they may also appear as
  // keyword_identifiers (dict keys, method names) without confusing
  // tree-sitter.
  "ask_user",
  "dual_control",
  "escalate_to",
  "request_approval",
];
