#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
tmp_root=$(mktemp -d)
trap 'rm -rf "$tmp_root"' EXIT

work="$tmp_root/work"
git init --initial-branch main --quiet "$work"
git -C "$work" config user.email "test@example.com"
git -C "$work" config user.name "Test User"
git -C "$work" config commit.gpgsign false
git -C "$work" config merge.harn-generated.driver true

mkdir -p "$work/crates/harn-stdlib/src/stdlib/cli/providers"
mkdir -p "$work/crates/harn-stdlib/src/stdlib/cli/models"
mkdir -p "$work/crates/harn-cli/generated/cli-bytecode"
cp "$repo_root/.gitattributes" "$work/.gitattributes"

printf '%s\n' 'base provider source' \
  > "$work/crates/harn-stdlib/src/stdlib/cli/providers/tool_scorecard.harn"
printf '%s\n' 'base model source' \
  > "$work/crates/harn-stdlib/src/stdlib/cli/models/list.harn"
printf '%s\n' 'base manifest' > "$work/crates/harn-cli/generated/cli-bytecode-manifest.json"
printf '%s\n' 'base table' > "$work/crates/harn-cli/generated/cli_bytecode_table.rs"
printf '\0base-provider' > "$work/crates/harn-cli/generated/cli-bytecode/providers-tool_scorecard.harnbc"
printf '\0base-model' > "$work/crates/harn-cli/generated/cli-bytecode/models-list.harnbc"
git -C "$work" add .
git -C "$work" commit --quiet -m "base"

git -C "$work" checkout --quiet -b feature
printf '%s\n' 'feature provider source' \
  > "$work/crates/harn-stdlib/src/stdlib/cli/providers/tool_scorecard.harn"
printf '%s\n' 'feature manifest' > "$work/crates/harn-cli/generated/cli-bytecode-manifest.json"
printf '%s\n' 'feature table' > "$work/crates/harn-cli/generated/cli_bytecode_table.rs"
printf '\0feature-provider' > "$work/crates/harn-cli/generated/cli-bytecode/providers-tool_scorecard.harnbc"
git -C "$work" add .
git -C "$work" commit --quiet -m "feature source and generated bytecode"

git -C "$work" checkout --quiet main
printf '%s\n' 'main model source' \
  > "$work/crates/harn-stdlib/src/stdlib/cli/models/list.harn"
printf '%s\n' 'main manifest' > "$work/crates/harn-cli/generated/cli-bytecode-manifest.json"
printf '%s\n' 'main table' > "$work/crates/harn-cli/generated/cli_bytecode_table.rs"
# CLI bytecode embeds the shared stdlib graph, so this unrelated model edit
# also changes the provider artifact on the current side.
printf '\0main-provider' > "$work/crates/harn-cli/generated/cli-bytecode/providers-tool_scorecard.harnbc"
printf '\0main-model' > "$work/crates/harn-cli/generated/cli-bytecode/models-list.harnbc"
git -C "$work" add .
git -C "$work" commit --quiet -m "main source and generated bytecode"

git -C "$work" merge --quiet --no-edit feature

if [[ "$(<"$work/crates/harn-stdlib/src/stdlib/cli/providers/tool_scorecard.harn")" != "feature provider source" ]]; then
  echo "feature authoring source was not merged" >&2
  exit 1
fi
if [[ "$(<"$work/crates/harn-stdlib/src/stdlib/cli/models/list.harn")" != "main model source" ]]; then
  echo "current authoring source changed unexpectedly" >&2
  exit 1
fi
if [[ "$(<"$work/crates/harn-cli/generated/cli-bytecode-manifest.json")" != "main manifest" ]]; then
  echo "generated manifest did not retain the current side" >&2
  exit 1
fi
if [[ "$(<"$work/crates/harn-cli/generated/cli_bytecode_table.rs")" != "main table" ]]; then
  echo "generated bytecode table did not retain the current side" >&2
  exit 1
fi
if ! printf '\0main-provider' | cmp -s - "$work/crates/harn-cli/generated/cli-bytecode/providers-tool_scorecard.harnbc"; then
  echo "feature bytecode did not retain the current side" >&2
  exit 1
fi
if ! printf '\0main-model' | cmp -s - "$work/crates/harn-cli/generated/cli-bytecode/models-list.harnbc"; then
  echo "current bytecode changed unexpectedly" >&2
  exit 1
fi
if [[ -n "$(git -C "$work" ls-files -u)" ]]; then
  echo "CLI AOT merge left unresolved paths" >&2
  exit 1
fi

for path in \
  crates/harn-cli/generated/cli-bytecode-manifest.json \
  crates/harn-cli/generated/cli_bytecode_table.rs \
  crates/harn-cli/generated/cli-bytecode/providers-tool_scorecard.harnbc; do
  if ! git -C "$work" check-attr merge -- "$path" | grep -Fxq "$path: merge: harn-generated"; then
    echo "CLI AOT path is not assigned the harn-generated merge driver: $path" >&2
    exit 1
  fi
done

echo "cli_aot_merge_driver_test: ok"
