[package]
name = "harn-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Parser, AST, and type checker for the Harn programming language"

[dependencies]
harn-builtin-meta = { path = "../harn-builtin-meta", version = "=0.10.8" }
harn-builtin-registry = { path = "../harn-builtin-registry", version = "=0.10.8" }
harn-lexer = { path = "../harn-lexer", version = "=0.10.8" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
yansi = "1"

[lints]
workspace = true
