// GENERATED by `harn dump-protocol-artifacts` - do not edit by hand.
// Source: Harn adapter schemas and Rust wire vocabulary.

// Package harnprotocol mirrors the host/integrator surface generated for
// TypeScript, Swift, and Python. Field names match the wire JSON; optional
// fields use pointer types or `omitempty` so encoding/json round-trips
// produce minimal envelopes equivalent to the Rust adapters.
package harnprotocol

import "encoding/json"

// ArtifactVersion pins the Harn release that generated this binding.
const ArtifactVersion = "0.8.16"

// HarnAgentEventMethod is the JSON-RPC method for `_harn/agentEvent` notifications.
const HarnAgentEventMethod = "_harn/agentEvent"

// ACPSchemaCompatibility is the upstream ACP schema version Harn tracks.
const ACPSchemaCompatibility = "agentclientprotocol/agent-client-protocol schema v0.12.2"

// A2AProtocolVersion is the A2A protocol version Harn implements.
const A2AProtocolVersion = "0.3.0"

// MCPProtocolVersion is the MCP protocol version Harn implements.
const MCPProtocolVersion = "2025-11-25"

// ACPAgentMethod is the typed alias for the ACPAgentMethods wire vocabulary.
type ACPAgentMethod = string

// ACPAgentMethods enumerates every wire value Harn currently emits for ACPAgentMethod.
var ACPAgentMethods = []ACPAgentMethod{
	"initialize",
	"session/new",
	"session/prompt",
	"session/stop",
}

// ACPClientMethod is the typed alias for the ACPClientMethods wire vocabulary.
type ACPClientMethod = string

// ACPClientMethods enumerates every wire value Harn currently emits for ACPClientMethod.
var ACPClientMethods = []ACPClientMethod{
	"fs/read_text_file",
	"fs/write_text_file",
	"terminal/create",
	"terminal/kill",
	"session/request_permission",
}

// ACPAgentNotification is the typed alias for the ACPAgentNotifications wire vocabulary.
type ACPAgentNotification = string

// ACPAgentNotifications enumerates every wire value Harn currently emits for ACPAgentNotification.
var ACPAgentNotifications = []ACPAgentNotification{
	"session/message",
	"session/update",
	"terminal/output",
}

// ACPSessionUpdate is the typed alias for the ACPSessionUpdates wire vocabulary.
type ACPSessionUpdate = string

// ACPSessionUpdates enumerates every wire value Harn currently emits for ACPSessionUpdate.
var ACPSessionUpdates = []ACPSessionUpdate{
	"user_message_chunk",
	"agent_message_chunk",
	"agent_thought_chunk",
	"tool_call",
	"tool_call_update",
	"plan",
	"available_commands_update",
	"current_mode_update",
	"config_option_update",
	"session_info_update",
	"fs_watch",
	"handoff",
	"hitl_request",
	"hitl_resolved",
	"log",
	"progress",
	"skill_activated",
	"skill_deactivated",
	"skill_scope_tools",
	"tool_search_query",
	"tool_search_result",
	"transcript_compacted",
	"worker_update",
}

// HarnACPSessionUpdateExtension is the typed alias for the HarnACPSessionUpdateExtensions wire vocabulary.
type HarnACPSessionUpdateExtension = string

// HarnACPSessionUpdateExtensions enumerates every wire value Harn currently emits for HarnACPSessionUpdateExtension.
var HarnACPSessionUpdateExtensions = []HarnACPSessionUpdateExtension{
	"available_commands_update",
	"fs_watch",
	"handoff",
	"hitl_request",
	"hitl_resolved",
	"log",
	"progress",
	"skill_activated",
	"skill_deactivated",
	"skill_scope_tools",
	"tool_search_query",
	"tool_search_result",
	"transcript_compacted",
	"worker_update",
}

// HarnAgentEventKind is the typed alias for the HarnAgentEventKinds wire vocabulary.
type HarnAgentEventKind = string

// HarnAgentEventKinds enumerates every wire value Harn currently emits for HarnAgentEventKind.
var HarnAgentEventKinds = []HarnAgentEventKind{
	"budget_exhausted",
	"daemon_watchdog_tripped",
	"feedback_injected",
	"judge_decision",
	"loop_control_decision",
	"loop_stuck",
	"session_closed",
	"tool_call_audit",
	"typed_checkpoint",
	"turn_end",
	"turn_start",
}

// ACPContentBlockType is the typed alias for the ACPContentBlockTypes wire vocabulary.
type ACPContentBlockType = string

// ACPContentBlockTypes enumerates every wire value Harn currently emits for ACPContentBlockType.
var ACPContentBlockTypes = []ACPContentBlockType{
	"text",
	"resource_link",
	"resource",
	"image",
	"audio",
}

// ACPToolKind is the typed alias for the ACPToolKinds wire vocabulary.
type ACPToolKind = string

// ACPToolKinds enumerates every wire value Harn currently emits for ACPToolKind.
var ACPToolKinds = []ACPToolKind{
	"read",
	"edit",
	"delete",
	"move",
	"search",
	"execute",
	"think",
	"fetch",
	"other",
}

// ACPToolCallStatus is the typed alias for the ACPToolCallStatuses wire vocabulary.
type ACPToolCallStatus = string

// ACPToolCallStatuses enumerates every wire value Harn currently emits for ACPToolCallStatus.
var ACPToolCallStatuses = []ACPToolCallStatus{
	"pending",
	"in_progress",
	"completed",
	"failed",
}

// HarnToolCallErrorCategory is the typed alias for the HarnToolCallErrorCategories wire vocabulary.
type HarnToolCallErrorCategory = string

// HarnToolCallErrorCategories enumerates every wire value Harn currently emits for HarnToolCallErrorCategory.
var HarnToolCallErrorCategories = []HarnToolCallErrorCategory{
	"schema_validation",
	"tool_error",
	"mcp_server_error",
	"host_bridge_error",
	"permission_denied",
	"rejected_loop",
	"parse_aborted",
	"timeout",
	"network",
	"cancelled",
	"unknown",
}

// HarnSideEffectLevel is the typed alias for the HarnSideEffectLevels wire vocabulary.
type HarnSideEffectLevel = string

// HarnSideEffectLevels enumerates every wire value Harn currently emits for HarnSideEffectLevel.
var HarnSideEffectLevels = []HarnSideEffectLevel{
	"none",
	"read_only",
	"workspace_write",
	"process_exec",
	"network",
}

// HarnWorkerStatus is the typed alias for the HarnWorkerStatuses wire vocabulary.
type HarnWorkerStatus = string

// HarnWorkerStatuses enumerates every wire value Harn currently emits for HarnWorkerStatus.
var HarnWorkerStatuses = []HarnWorkerStatus{
	"running",
	"progressed",
	"awaiting_input",
	"completed",
	"failed",
	"cancelled",
}

// A2ATaskState is the typed alias for the A2ATaskStates wire vocabulary.
type A2ATaskState = string

// A2ATaskStates enumerates every wire value Harn currently emits for A2ATaskState.
var A2ATaskStates = []A2ATaskState{
	"submitted",
	"working",
	"completed",
	"failed",
	"canceled",
	"cancelled",
	"input-required",
	"rejected",
	"auth-required",
}

// A2ATaskEventType is the typed alias for the A2ATaskEventTypes wire vocabulary.
type A2ATaskEventType = string

// A2ATaskEventTypes enumerates every wire value Harn currently emits for A2ATaskEventType.
var A2ATaskEventTypes = []A2ATaskEventType{
	"status",
	"message",
	"worker_update",
}

// MCPMethod is the typed alias for the MCPMethods wire vocabulary.
type MCPMethod = string

// MCPMethods enumerates every wire value Harn currently emits for MCPMethod.
var MCPMethods = []MCPMethod{
	"initialize",
	"tools/list",
	"tools/call",
	"resources/list",
	"resources/read",
	"resources/templates/list",
	"prompts/list",
	"prompts/get",
	"completion/complete",
	"logging/setLevel",
	"sampling/createMessage",
	"elicitation/create",
	"notifications/initialized",
	"notifications/message",
}

// MCPLoggingLevel is the typed alias for the MCPLoggingLevels wire vocabulary.
type MCPLoggingLevel = string

// MCPLoggingLevels enumerates every wire value Harn currently emits for MCPLoggingLevel.
var MCPLoggingLevels = []MCPLoggingLevel{
	"debug",
	"info",
	"notice",
	"warning",
	"error",
	"critical",
	"alert",
	"emergency",
}

// HarnToolLifecycleExtensionFields enumerates the wire values Harn currently emits.
var HarnToolLifecycleExtensionFields = []string{
	"audit",
	"durationMs",
	"error",
	"errorCategory",
	"executionDurationMs",
	"executor",
	"parsing",
	"rawInputPartial",
}

// HarnContentExtensionFields enumerates the wire values Harn currently emits.
var HarnContentExtensionFields = []string{
	"visible_delta",
	"visible_text",
}

// A2AMethods enumerates the wire values Harn currently emits.
var A2AMethods = []string{
	"message/send",
	"message/stream",
	"tasks/get",
	"tasks/cancel",
	"tasks/resubscribe",
	"tasks/pushNotificationConfig/set",
	"tasks/pushNotificationConfig/get",
	"tasks/pushNotificationConfig/list",
	"tasks/pushNotificationConfig/delete",
	"agent/getAuthenticatedExtendedCard",
}

// JSONValue is the Go counterpart of the TypeScript ACPValue / Python JsonValue
// type. Concrete fields generally use json.RawMessage so callers can defer
// decoding to their own dataclasses.
type JSONValue = json.RawMessage

// JSONObject mirrors `Record<string, JsonValue>`.
type JSONObject = map[string]json.RawMessage

// JSONRPCID encodes a JSON-RPC id, which may be an integer, a string, or null.
// Use NewJSONRPCIDInt / NewJSONRPCIDString to construct, or NullJSONRPCID for
// the null variant.
type JSONRPCID struct {
	raw     json.RawMessage
	present bool
}

// NewJSONRPCIDInt builds a JSON-RPC id from an integer.
func NewJSONRPCIDInt(value int64) JSONRPCID {
	bytes, _ := json.Marshal(value)
	return JSONRPCID{raw: bytes, present: true}
}

// NewJSONRPCIDString builds a JSON-RPC id from a string.
func NewJSONRPCIDString(value string) JSONRPCID {
	bytes, _ := json.Marshal(value)
	return JSONRPCID{raw: bytes, present: true}
}

// NullJSONRPCID returns a JSON-RPC id explicitly encoded as null.
func NullJSONRPCID() JSONRPCID {
	return JSONRPCID{raw: json.RawMessage("null"), present: true}
}

// IsPresent reports whether the id field was present on the wire.
func (id JSONRPCID) IsPresent() bool { return id.present }

// MarshalJSON implements json.Marshaler.
func (id JSONRPCID) MarshalJSON() ([]byte, error) {
	if !id.present {
		return []byte("null"), nil
	}
	return id.raw, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (id *JSONRPCID) UnmarshalJSON(data []byte) error {
	id.raw = append(id.raw[:0], data...)
	id.present = true
	return nil
}

// Raw exposes the encoded bytes for callers that need to inspect the variant.
func (id JSONRPCID) Raw() json.RawMessage { return id.raw }

// ACPRequest is a JSON-RPC request envelope.
type ACPRequest struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      JSONRPCID       `json:"id"`
	Method  string          `json:"method"`
	Params  json.RawMessage `json:"params,omitempty"`
}

// ACPError is the JSON-RPC error sub-envelope.
type ACPError struct {
	Code    int             `json:"code"`
	Message string          `json:"message"`
	Data    json.RawMessage `json:"data,omitempty"`
}

// ACPResponse is a JSON-RPC response envelope.
type ACPResponse struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      JSONRPCID       `json:"id"`
	Result  json.RawMessage `json:"result,omitempty"`
	Error   *ACPError       `json:"error,omitempty"`
}

// ACPNotification is a JSON-RPC notification envelope.
type ACPNotification struct {
	JSONRPC string          `json:"jsonrpc"`
	Method  string          `json:"method"`
	Params  json.RawMessage `json:"params,omitempty"`
}

// HarnExtensionMeta is the canonical envelope for `_meta.harn` payloads.
type HarnExtensionMeta struct {
	Harn JSONObject `json:"harn,omitempty"`
}

// ACPContentBlock is one element inside a session update or message content array.
type ACPContentBlock struct {
	Type string             `json:"type"`
	Text *string            `json:"text,omitempty"`
	Meta *HarnExtensionMeta `json:"_meta,omitempty"`
}

// HarnToolLifecycleMeta is the Harn-specific tool-call lifecycle metadata
// living under `_meta.harn` on tool_call / tool_call_update notifications.
type HarnToolLifecycleMeta struct {
	Audit               json.RawMessage `json:"audit,omitempty"`
	DurationMs          *float64        `json:"durationMs,omitempty"`
	Error               *string         `json:"error,omitempty"`
	ErrorCategory       *string         `json:"errorCategory,omitempty"`
	ExecutionDurationMs *float64        `json:"executionDurationMs,omitempty"`
	Executor            json.RawMessage `json:"executor,omitempty"`
	Parsing             *bool           `json:"parsing,omitempty"`
	RawInputPartial     *string         `json:"rawInputPartial,omitempty"`
}

// ACPToolCall is the `tool_call` session update.
type ACPToolCall struct {
	SessionUpdate string             `json:"sessionUpdate"`
	ToolCallID    string             `json:"toolCallId"`
	Title         string             `json:"title"`
	Kind          *string            `json:"kind,omitempty"`
	Status        *string            `json:"status,omitempty"`
	Content       []ACPContentBlock  `json:"content,omitempty"`
	Locations     []json.RawMessage  `json:"locations,omitempty"`
	RawInput      json.RawMessage    `json:"rawInput,omitempty"`
	RawOutput     json.RawMessage    `json:"rawOutput,omitempty"`
	Meta          *HarnExtensionMeta `json:"_meta,omitempty"`
}

// ACPToolCallUpdate is the `tool_call_update` session update.
type ACPToolCallUpdate struct {
	SessionUpdate string             `json:"sessionUpdate"`
	ToolCallID    string             `json:"toolCallId"`
	Title         *string            `json:"title,omitempty"`
	Kind          *string            `json:"kind,omitempty"`
	Status        *string            `json:"status,omitempty"`
	Content       []ACPContentBlock  `json:"content,omitempty"`
	Locations     []json.RawMessage  `json:"locations,omitempty"`
	RawInput      json.RawMessage    `json:"rawInput,omitempty"`
	RawOutput     json.RawMessage    `json:"rawOutput,omitempty"`
	Meta          *HarnExtensionMeta `json:"_meta,omitempty"`
}

// ACPSessionUpdateEnvelope is the discriminated `update` payload carried inside
// an ACP `session/update` notification. Only fields relevant to a given
// `sessionUpdate` discriminator will be populated; the rest stay zero-value
// and are stripped via `omitempty` on serialization.
type ACPSessionUpdateEnvelope struct {
	SessionUpdate string             `json:"sessionUpdate"`
	Content       *ACPContentBlock   `json:"content,omitempty"`
	Entries       []json.RawMessage  `json:"entries,omitempty"`
	ToolCallID    *string            `json:"toolCallId,omitempty"`
	Title         *string            `json:"title,omitempty"`
	Kind          *string            `json:"kind,omitempty"`
	Status        *string            `json:"status,omitempty"`
	RawInput      json.RawMessage    `json:"rawInput,omitempty"`
	RawOutput     json.RawMessage    `json:"rawOutput,omitempty"`
	Meta          *HarnExtensionMeta `json:"_meta,omitempty"`
}

// ACPSessionUpdateParams is the params payload of `session/update`.
type ACPSessionUpdateParams struct {
	SessionID string                   `json:"sessionId"`
	Update    ACPSessionUpdateEnvelope `json:"update"`
}

// ACPSessionUpdateNotification is the full `session/update` envelope.
type ACPSessionUpdateNotification struct {
	JSONRPC string                 `json:"jsonrpc"`
	Method  string                 `json:"method"`
	Params  ACPSessionUpdateParams `json:"params"`
}

// HarnAgentEventNotification is the `_harn/agentEvent` envelope.
type HarnAgentEventNotification struct {
	JSONRPC string     `json:"jsonrpc"`
	Method  string     `json:"method"`
	Params  JSONObject `json:"params"`
}

// HarnToolArgSchema describes the static slice of a Harn tool's argument shape.
type HarnToolArgSchema struct {
	PathParams []string          `json:"path_params"`
	ArgAliases map[string]string `json:"arg_aliases"`
	Required   []string          `json:"required"`
}

// HarnToolAnnotations describes Harn-side metadata for a tool.
type HarnToolAnnotations struct {
	Kind            string              `json:"kind"`
	SideEffectLevel string              `json:"side_effect_level"`
	ArgSchema       HarnToolArgSchema   `json:"arg_schema"`
	Capabilities    map[string][]string `json:"capabilities"`
	EmitsArtifacts  bool                `json:"emits_artifacts"`
	ResultReaders   []string            `json:"result_readers"`
	InlineResult    bool                `json:"inline_result"`
}

// A2AMessage is one message inside an A2A task history.
type A2AMessage struct {
	ID    string            `json:"id"`
	Role  string            `json:"role"`
	Parts []json.RawMessage `json:"parts"`
}

// A2ATaskStatus is the status block on an A2A task.
type A2ATaskStatus struct {
	State     string      `json:"state"`
	Message   *A2AMessage `json:"message,omitempty"`
	Timestamp *string     `json:"timestamp,omitempty"`
}

// A2ATask is the canonical A2A task envelope.
type A2ATask struct {
	ID        string            `json:"id"`
	ContextID *string           `json:"contextId,omitempty"`
	Status    A2ATaskStatus     `json:"status"`
	History   []A2AMessage      `json:"history,omitempty"`
	Artifacts []json.RawMessage `json:"artifacts,omitempty"`
	Metadata  JSONObject        `json:"metadata,omitempty"`
}

// MCPTool is the MCP `tools/list` entry.
type MCPTool struct {
	Name         string     `json:"name"`
	Title        *string    `json:"title,omitempty"`
	Description  *string    `json:"description,omitempty"`
	InputSchema  JSONObject `json:"inputSchema"`
	OutputSchema JSONObject `json:"outputSchema,omitempty"`
	Annotations  JSONObject `json:"annotations,omitempty"`
}

// MCPResource is the MCP `resources/list` entry.
type MCPResource struct {
	URI         string  `json:"uri"`
	Name        string  `json:"name"`
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	MimeType    *string `json:"mimeType,omitempty"`
}

// MCPResourceTemplate is the MCP `resources/templates/list` entry.
type MCPResourceTemplate struct {
	URITemplate string  `json:"uriTemplate"`
	Name        string  `json:"name"`
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	MimeType    *string `json:"mimeType,omitempty"`
}

// MCPPrompt is the MCP `prompts/list` entry.
type MCPPrompt struct {
	Name        string       `json:"name"`
	Title       *string      `json:"title,omitempty"`
	Description *string      `json:"description,omitempty"`
	Arguments   []JSONObject `json:"arguments,omitempty"`
}

// IsRequest reports whether a decoded JSON-RPC envelope is a request.
func IsRequest(envelope map[string]json.RawMessage) bool {
	_, hasID := envelope["id"]
	_, hasMethod := envelope["method"]
	return hasID && hasMethod
}

// IsResponse reports whether a decoded JSON-RPC envelope is a response.
func IsResponse(envelope map[string]json.RawMessage) bool {
	_, hasID := envelope["id"]
	_, hasMethod := envelope["method"]
	return hasID && !hasMethod
}

// IsNotification reports whether a decoded JSON-RPC envelope is a notification.
func IsNotification(envelope map[string]json.RawMessage) bool {
	_, hasID := envelope["id"]
	_, hasMethod := envelope["method"]
	return !hasID && hasMethod
}
