import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

import { KEYWORD_DOCS } from "./keyword-docs"

// docs/theme/harn-keywords.js is generated by `make gen-highlight` from the live
// lexer keywords + stdlib builtin names and is CI-gated (check-highlight), so it
// is the source of truth for which identifiers exist. KEYWORD_DOCS is
// hand-maintained tooltip copy keyed by those identifiers; a key that is neither
// a keyword, a literal, nor a builtin is drift. Pin it here so a stale entry (a
// removed keyword, a misspelled builtin) fails CI instead of shipping.
function generatedVocabulary(): Set<string> {
  const source = readFileSync(
    new URL("../../../docs/theme/harn-keywords.js", import.meta.url),
    "utf8",
  )
  const field = (name: string): string[] => {
    const match = source.match(new RegExp(`${name}:\\s*"([^"]*)"`))
    return (match?.[1] ?? "").split(/\s+/).filter(Boolean)
  }
  const tokens = [...field("keyword"), ...field("literal"), ...field("built_in")]
  expect(tokens.length).toBeGreaterThan(0)
  return new Set(tokens)
}

describe("KEYWORD_DOCS", () => {
  it("only documents identifiers the generated highlighter knows", () => {
    const vocabulary = generatedVocabulary()
    const unknown = Object.keys(KEYWORD_DOCS).filter((key) => !vocabulary.has(key))
    expect(unknown).toEqual([])
  })
})
