#!/usr/bin/env bash
# Public stdlib return-type ratchet.
#
# The policy authority is the Harn AST/linter: this script asks `harn lint
# --json` for HARN-STD-102 diagnostics, extracts stable `path::function` keys
# from those diagnostics, and compares them with the checked-in baseline. It
# never scans source text for `pub fn` or `->`.
set -euo pipefail

STDLIB_DIR="crates/harn-stdlib/src/stdlib"
BASELINE="scripts/stdlib-public-return-type-baseline.txt"
CODE="HARN-STD-102"

mode="check"
if [[ "${1:-}" == "--update-baseline" ]]; then
  mode="update"
elif [[ $# -gt 0 ]]; then
  echo "usage: $0 [--update-baseline]" >&2
  exit 2
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required for the stdlib return-type ratchet" >&2
  exit 1
fi

harn_bin="$(./scripts/harn_bin.sh --no-build --print)"
json_tmp="$(mktemp)"
actual_tmp="$(mktemp)"
expected_tmp="$(mktemp)"
baseline_tmp="$(mktemp)"
cleanup() {
  rm -f "$json_tmp" "$actual_tmp" "$expected_tmp" "$baseline_tmp"
}
trap cleanup EXIT

"$harn_bin" lint --json "$STDLIB_DIR" >"$json_tmp" 2>&1 || true

jq -r --arg code "$CODE" '
  def payload: .data? // .result? // .;
  payload.files[]
  | .path as $path
  | .diagnostics[]
  | select(.code == $code)
  | ($path + "::" + (.message | capture("`(?<name>[^`]+)`").name))
' "$json_tmp" | LC_ALL=C sort -u >"$actual_tmp"

if [[ "$mode" == "update" ]]; then
  {
    echo "# Public stdlib functions without explicit return annotations."
    echo "# Generated by scripts/check_stdlib_public_return_types.sh --update-baseline."
    echo "# Source of truth: Harn AST diagnostics (HARN-STD-102) from harn lint --json."
    echo "# Entries are repo-relative path::public_function_name; comments below give per-module counts."
    echo "# Split-module note: selected internal helpers are public because Harn currently"
    echo "# crosses module boundaries through public exports; keep their contracts in this"
    echo "# ratchet until private cross-module imports or explicit return types are available."
    echo "#"
    awk -F'::' '
      { counts[$1]++ }
      END {
        for (path in counts) {
          print counts[path] "\t" path
        }
      }
    ' "$actual_tmp" | LC_ALL=C sort -k2,2 | awk -F'\t' '{ printf("# count %4d  %s\n", $1, $2) }'
    echo
    cat "$actual_tmp"
  } >"$baseline_tmp"
  mv "$baseline_tmp" "$BASELINE"
  echo "updated $BASELINE with $(wc -l < "$actual_tmp" | tr -d ' ') HARN-STD-102 baseline entries"
  exit 0
fi

if [[ ! -f "$BASELINE" ]]; then
  echo "missing stdlib return-type baseline: $BASELINE" >&2
  echo "run $0 --update-baseline and commit the generated file" >&2
  exit 1
fi

awk '!/^[[:space:]]*(#|$)/ { print }' "$BASELINE" | LC_ALL=C sort -u >"$expected_tmp"

new_tmp="$(mktemp)"
resolved_tmp="$(mktemp)"
trap 'cleanup; rm -f "$new_tmp" "$resolved_tmp"' EXIT
comm -13 "$expected_tmp" "$actual_tmp" >"$new_tmp"
comm -23 "$expected_tmp" "$actual_tmp" >"$resolved_tmp"

if [[ -s "$new_tmp" || -s "$resolved_tmp" ]]; then
  if [[ -s "$new_tmp" ]]; then
    echo "stdlib public return-type ratchet failed: new unannotated public exports:" >&2
    sed 's/^/  /' "$new_tmp" >&2
  fi
  if [[ -s "$resolved_tmp" ]]; then
    echo "stdlib public return-type baseline is stale; remove resolved entries:" >&2
    sed 's/^/  /' "$resolved_tmp" >&2
  fi
  echo >&2
  echo "Add honest return annotations, or run $0 --update-baseline only as part of an intentional migration-wave commit." >&2
  exit 1
fi

entry_count="$(wc -l < "$actual_tmp" | tr -d ' ')"
module_count="$(cut -d: -f1 "$actual_tmp" | LC_ALL=C sort -u | wc -l | tr -d ' ')"
echo "stdlib public return-type ratchet passed: $entry_count baseline entries across $module_count modules."
