#!/usr/bin/env python3
"""Check the Harn Agents OpenAPI path/schema surface snapshot."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "spec" / "openapi.yaml"
SNAPSHOT_PATH = ROOT / "spec" / "openapi.snapshot"
HTTP_METHODS = {"get", "put", "post", "delete", "patch", "options", "head", "trace"}


def collect_surface(spec_text: str) -> str:
    paths: list[str] = []
    schemas: list[str] = []
    section: str | None = None
    current_path: str | None = None

    for line in spec_text.splitlines():
        if re.match(r"^[A-Za-z][A-Za-z0-9_-]*:", line):
            section = line[:-1]
            current_path = None
            continue

        if section == "paths":
            path_match = re.match(r"^  (/[^\s]+):$", line)
            if path_match:
                current_path = path_match.group(1)
                continue
            method_match = re.match(r"^    ([a-z]+):$", line)
            if current_path and method_match and method_match.group(1) in HTTP_METHODS:
                paths.append(f"{method_match.group(1).upper()} {current_path}")
                continue

        if section == "components":
            if line == "  schemas:":
                section = "schemas"
                continue

        if section == "schemas":
            schema_match = re.match(r"^    ([A-Za-z][A-Za-z0-9_]*):$", line)
            if schema_match:
                schemas.append(schema_match.group(1))

    return "\n".join(
        [
            "# Generated by scripts/check_openapi_snapshot.py --update",
            "",
            "## Paths",
            *paths,
            "",
            "## Schemas",
            *schemas,
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--update", action="store_true", help="rewrite the snapshot")
    args = parser.parse_args()

    actual = collect_surface(SPEC_PATH.read_text())
    if args.update:
        SNAPSHOT_PATH.write_text(actual)
        return 0

    expected = SNAPSHOT_PATH.read_text() if SNAPSHOT_PATH.exists() else ""
    if actual == expected:
        return 0

    print(
        "spec/openapi.snapshot is stale. Run "
        "`./scripts/check_openapi_snapshot.py --update` after reviewing the OpenAPI surface.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
