//! Connector, host, tool, and shell-facing builtin signatures.

use super::{
    BuiltinSignature, Param, Ty, TY_ANY, TY_BOOL, TY_BYTES_OR_NIL, TY_CLOSURE, TY_DICT,
    TY_DICT_OR_NIL, TY_INT, TY_LIST, TY_NIL, TY_NUMBER, TY_STRING, TY_STRING_OR_NIL,
};

const TY_STRING_OR_DICT: Ty = Ty::Union(&[TY_STRING, TY_DICT]);
const TY_TOOL_REGISTRY: Ty = Ty::Union(&[TY_DICT, TY_CLOSURE]);

pub(crate) const SIGNATURES: &[BuiltinSignature] = &[
    BuiltinSignature {
        name: "connector_call",
        params: &[
            Param::new("provider", TY_STRING),
            Param::new("method", TY_STRING),
            Param::optional("params", TY_DICT),
        ],
        returns: TY_ANY,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "connector_shared_verify_jwt_inline",
        params: &[
            Param::new("token", TY_STRING),
            Param::new("jwks", TY_DICT),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "egress_policy",
        params: &[Param::new("config", TY_DICT)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "exec",
        params: &[Param::new("command", TY_STRING)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: true,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "exec_at",
        params: &[
            Param::new("dir", TY_STRING),
            Param::new("command", TY_STRING),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: true,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "git.conflicts",
        params: &[Param::new("repo", TY_STRING)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "git.diff",
        params: &[
            Param::new("repo", TY_STRING),
            Param::optional("selector", TY_ANY),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "git.fetch",
        params: &[
            Param::new("repo", TY_STRING),
            Param::new("remote", TY_STRING),
            Param::optional("refspecs", TY_LIST),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "git.merge_base",
        params: &[
            Param::new("repo", TY_STRING),
            Param::new("left", TY_STRING),
            Param::new("right", TY_STRING),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "git.push",
        params: &[
            Param::new("repo", TY_STRING),
            Param::new("remote", TY_STRING),
            Param::new("refspec", TY_STRING),
            Param::optional("lease", TY_ANY),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "git.rebase",
        params: &[
            Param::new("repo", TY_STRING),
            Param::new("base_ref", TY_STRING),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "git.repo.discover",
        params: &[Param::new("path", TY_STRING)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "git.status",
        params: &[Param::new("repo", TY_STRING)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "git.worktree.create",
        params: &[
            Param::new("repo", TY_STRING),
            Param::new("branch", TY_STRING),
            Param::new("path", TY_STRING),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "git.worktree.remove",
        params: &[
            Param::new("path", TY_STRING),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "harn.mcp.roots",
        params: &[],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "host_call",
        params: &[
            Param::new("name", TY_STRING),
            Param::optional("params", TY_DICT),
        ],
        returns: TY_ANY,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "host_capabilities",
        params: &[],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "host_has",
        params: &[
            Param::new("capability", TY_STRING),
            Param::optional("operation", TY_STRING),
        ],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "host_mock",
        params: &[
            Param::new("capability", TY_STRING),
            Param::new("operation", TY_STRING),
            Param::optional("result_or_config", TY_ANY),
            Param::optional("params", TY_DICT),
        ],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "host_mock_calls",
        params: &[],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "host_mock_clear",
        params: &[],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "host_mock_pop_scope",
        params: &[],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "host_mock_push_scope",
        params: &[],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "host_tool_call",
        params: &[
            Param::new("name", TY_STRING),
            Param::optional("args", TY_ANY),
        ],
        returns: TY_ANY,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "host_tool_list",
        params: &[],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_delete",
        params: &[
            Param::new("url", TY_STRING),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_download",
        params: &[
            Param::new("url", TY_STRING),
            Param::new("dst_path", TY_STRING),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_get",
        params: &[
            Param::new("url", TY_STRING),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_header",
        params: &[
            Param::new("source", Ty::Union(&[TY_DICT, TY_LIST])),
            Param::new("name", TY_STRING),
        ],
        returns: TY_STRING_OR_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_mock",
        params: &[
            Param::new("method", TY_STRING),
            Param::new("url_pattern", TY_STRING),
            Param::optional("response", TY_DICT),
        ],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_mock_calls",
        params: &[Param::optional("options", TY_DICT)],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_mock_clear",
        params: &[],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_patch",
        params: &[
            Param::new("url", TY_STRING),
            Param::optional("body_or_options", TY_ANY),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_post",
        params: &[
            Param::new("url", TY_STRING),
            Param::optional("body_or_options", TY_ANY),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_put",
        params: &[
            Param::new("url", TY_STRING),
            Param::optional("body_or_options", TY_ANY),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_request",
        params: &[
            Param::new("method", TY_STRING),
            Param::new("url", TY_STRING),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_response",
        params: &[
            Param::optional("status", TY_INT),
            Param::optional("body", TY_ANY),
            Param::optional("headers", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_response_bytes",
        params: &[
            Param::optional("body", TY_ANY),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_response_json",
        params: &[
            Param::optional("body", TY_ANY),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_response_text",
        params: &[
            Param::optional("body", TY_ANY),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server",
        params: &[Param::optional("options", TY_DICT)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_after",
        params: &[
            Param::new("server", TY_DICT),
            Param::new("handler", TY_CLOSURE),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_before",
        params: &[
            Param::new("server", TY_DICT),
            Param::new("handler", TY_CLOSURE),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_on_shutdown",
        params: &[
            Param::new("server", TY_DICT),
            Param::new("handler", TY_CLOSURE),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_readiness",
        params: &[
            Param::new("server", TY_DICT),
            Param::new("handler", TY_CLOSURE),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_ready",
        params: &[Param::new("server", TY_DICT)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_request",
        params: &[
            Param::new("server", TY_DICT),
            Param::new("request", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_route",
        params: &[
            Param::new("server", TY_DICT),
            Param::new("method", TY_STRING),
            Param::new("template", TY_STRING),
            Param::new("handler", TY_CLOSURE),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_security_headers",
        params: &[Param::new("tls_config", TY_DICT)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_set_ready",
        params: &[Param::new("server", TY_DICT), Param::new("ready", TY_BOOL)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_shutdown",
        params: &[Param::new("server", TY_DICT)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_test",
        params: &[
            Param::new("server", TY_DICT),
            Param::new("request", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_tls_edge",
        params: &[Param::optional("options", TY_DICT)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_tls_pem",
        params: &[
            Param::new("cert_path", TY_STRING),
            Param::new("key_path", TY_STRING),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_tls_plain",
        params: &[],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_server_tls_self_signed_dev",
        params: &[Param::optional("hosts", Ty::Union(&[TY_LIST, TY_STRING]))],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_session",
        params: &[Param::optional("options", TY_DICT)],
        returns: TY_STRING,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_session_close",
        params: &[Param::new("session", TY_STRING)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_session_request",
        params: &[
            Param::new("session", TY_STRING),
            Param::new("method", TY_STRING),
            Param::new("url", TY_STRING),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_stream_close",
        params: &[Param::new("stream", TY_STRING)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_stream_info",
        params: &[Param::new("stream", TY_STRING)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_stream_open",
        params: &[
            Param::new("url", TY_STRING),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_STRING,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "http_stream_read",
        params: &[
            Param::new("stream", TY_STRING),
            Param::optional("max_bytes", TY_INT),
        ],
        returns: TY_BYTES_OR_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "list_providers_native",
        params: &[],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "load_skill",
        params: &[Param::new("name", TY_STRING)],
        returns: TY_STRING,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_call",
        params: &[
            Param::new("client", TY_ANY),
            Param::new("tool_name", TY_STRING),
            Param::optional("arguments", TY_DICT),
        ],
        returns: TY_ANY,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_connect",
        params: &[
            Param::new("command", TY_STRING),
            Param::optional("args", TY_LIST),
        ],
        returns: TY_ANY,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_disconnect",
        params: &[Param::new("client", TY_ANY)],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_elicit",
        params: &[Param::new("config", TY_DICT)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_ensure_active",
        params: &[Param::new("name", TY_STRING)],
        returns: TY_ANY,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_get_prompt",
        params: &[
            Param::new("client", TY_ANY),
            Param::new("name", TY_STRING),
            Param::optional("arguments", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_list_prompts",
        params: &[Param::new("client", TY_ANY)],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_list_resource_templates",
        params: &[Param::new("client", TY_ANY)],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_list_resources",
        params: &[Param::new("client", TY_ANY)],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_list_tools",
        params: &[Param::new("client", TY_ANY)],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_prompt",
        params: &[Param::new("config", TY_DICT)],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_read_resource",
        params: &[Param::new("client", TY_ANY), Param::new("uri", TY_STRING)],
        returns: Ty::Union(&[TY_STRING, TY_LIST, TY_NIL]),
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_registry_status",
        params: &[],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_release",
        params: &[Param::new("name", TY_STRING)],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_report_progress",
        params: &[
            Param::new("progress", TY_NUMBER),
            Param::optional("opts", TY_DICT),
        ],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_resource",
        params: &[Param::new("config", TY_DICT)],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_resource_template",
        params: &[Param::new("config", TY_DICT)],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_roots",
        params: &[],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_serve",
        params: &[Param::new("registry", TY_DICT)],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_server_card",
        params: &[Param::new("target", TY_STRING)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_server_info",
        params: &[Param::new("client", TY_ANY)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "mcp_tools",
        params: &[Param::new("registry", TY_DICT)],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "prompt_user",
        params: &[Param::optional("message", TY_STRING)],
        returns: TY_STRING_OR_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "provider_capabilities",
        params: &[
            Param::new("provider", TY_STRING),
            Param::optional("model", TY_STRING),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "provider_capabilities_clear",
        params: &[],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "provider_capabilities_install",
        params: &[Param::new("toml_src", TY_STRING)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "provider_register",
        params: &[Param::new("name", TY_STRING)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "runtime_paths",
        params: &[],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "shell",
        params: &[Param::new("command", TY_STRING)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "shell_at",
        params: &[
            Param::new("dir", TY_STRING),
            Param::new("command", TY_STRING),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "skill_count",
        params: &[Param::new("registry", TY_DICT)],
        returns: TY_INT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "skill_define",
        params: &[
            Param::new("registry", TY_DICT),
            Param::new("name", TY_STRING),
            Param::new("config", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "skill_describe",
        params: &[Param::new("registry", TY_DICT)],
        returns: TY_STRING,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "skill_find",
        params: &[
            Param::new("registry", TY_DICT),
            Param::new("name", TY_STRING),
        ],
        returns: TY_DICT_OR_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "skill_list",
        params: &[Param::new("registry", TY_DICT)],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "skill_registry",
        params: &[],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "skill_remove",
        params: &[
            Param::new("registry", TY_DICT),
            Param::new("name", TY_STRING),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "skill_render",
        params: &[
            Param::new("skill", Ty::Union(&[TY_DICT, TY_STRING])),
            Param::optional("arguments", TY_LIST),
        ],
        returns: TY_STRING,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "skill_select",
        params: &[
            Param::new("registry", TY_DICT),
            Param::new("names", TY_LIST),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "skills_catalog_entries",
        params: &[Param::new("registry", TY_DICT)],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_close",
        params: &[Param::new("stream", TY_STRING)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_connect",
        params: &[
            Param::optional("method", TY_STRING),
            Param::optional("url", TY_STRING),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_STRING,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_event",
        params: &[
            Param::new("event", TY_ANY),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_STRING,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_mock",
        params: &[
            Param::new("url_pattern", TY_STRING),
            Param::optional("events", TY_LIST),
        ],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_receive",
        params: &[
            Param::new("stream", TY_STRING),
            Param::optional("timeout_ms", TY_INT),
        ],
        returns: TY_DICT_OR_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_server_cancel",
        params: &[
            Param::new("stream", TY_STRING_OR_DICT),
            Param::optional("reason", TY_STRING),
        ],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_server_cancelled",
        params: &[Param::new("stream", TY_STRING_OR_DICT)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_server_close",
        params: &[Param::new("stream", TY_STRING_OR_DICT)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_server_disconnected",
        params: &[Param::new("stream", TY_STRING_OR_DICT)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_server_flush",
        params: &[Param::new("stream", TY_STRING_OR_DICT)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_server_heartbeat",
        params: &[
            Param::new("stream", TY_STRING_OR_DICT),
            Param::optional("comment", TY_STRING),
        ],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_server_mock_disconnect",
        params: &[Param::new("stream", TY_STRING_OR_DICT)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_server_mock_receive",
        params: &[Param::new("stream", TY_STRING_OR_DICT)],
        returns: TY_DICT_OR_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_server_response",
        params: &[Param::optional("options", TY_DICT)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_server_send",
        params: &[
            Param::new("stream", TY_STRING_OR_DICT),
            Param::new("event", TY_ANY),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "sse_server_status",
        params: &[Param::new("stream", TY_STRING_OR_DICT)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_bind",
        params: &[Param::optional("registry", TY_TOOL_REGISTRY)],
        returns: TY_DICT_OR_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_count",
        params: &[Param::new("registry", TY_TOOL_REGISTRY)],
        returns: TY_INT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_def",
        params: &[Param::new("name", TY_STRING)],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_define",
        params: &[
            Param::new("registry", TY_TOOL_REGISTRY),
            Param::new("name", TY_STRING),
            Param::new("description", TY_STRING),
            Param::new("config", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_describe",
        params: &[Param::new("registry", TY_TOOL_REGISTRY)],
        returns: TY_STRING,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_find",
        params: &[
            Param::new("registry", TY_TOOL_REGISTRY),
            Param::new("name", TY_STRING),
        ],
        returns: TY_DICT_OR_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_format_result",
        params: &[Param::new("name", TY_STRING), Param::new("result", TY_ANY)],
        returns: TY_STRING,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_list",
        params: &[Param::new("registry", TY_TOOL_REGISTRY)],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_parse_call",
        params: &[Param::new("text", TY_STRING)],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_prompt",
        params: &[Param::new("registry", TY_TOOL_REGISTRY)],
        returns: TY_STRING,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_ref",
        params: &[Param::new("name", TY_STRING)],
        returns: TY_STRING,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_registry",
        params: &[],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_remove",
        params: &[
            Param::new("registry", TY_TOOL_REGISTRY),
            Param::new("name", TY_STRING),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_schema",
        params: &[
            Param::new("registry", TY_TOOL_REGISTRY),
            Param::optional("components", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_select",
        params: &[
            Param::new("registry", TY_TOOL_REGISTRY),
            Param::new("names", TY_LIST),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_surface_validate",
        params: &[
            Param::optional("surface", TY_ANY),
            Param::optional("input", TY_ANY),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_synth_invoke",
        params: &[Param::new("id", TY_STRING), Param::optional("args", TY_ANY)],
        returns: TY_ANY,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_synthesis_cache",
        params: &[],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_synthesis_clear",
        params: &[],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "tool_synthesize",
        params: &[Param::new("spec", TY_DICT)],
        returns: TY_CLOSURE,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "transport_mock_calls",
        params: &[],
        returns: TY_LIST,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "transport_mock_clear",
        params: &[],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "websocket_accept",
        params: &[
            Param::new("server", TY_STRING_OR_DICT),
            Param::optional("timeout_ms", TY_INT),
        ],
        returns: TY_DICT_OR_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "websocket_close",
        params: &[Param::new("socket", TY_STRING_OR_DICT)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "websocket_connect",
        params: &[
            Param::new("url", TY_STRING),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_STRING,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "websocket_mock",
        params: &[
            Param::new("url_pattern", TY_STRING),
            Param::optional("config", TY_ANY),
        ],
        returns: TY_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "websocket_receive",
        params: &[
            Param::new("socket", TY_STRING_OR_DICT),
            Param::optional("timeout_ms", TY_INT),
        ],
        returns: TY_DICT_OR_NIL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "websocket_route",
        params: &[
            Param::new("server", TY_STRING_OR_DICT),
            Param::new("path", TY_STRING),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "websocket_send",
        params: &[
            Param::new("socket", TY_STRING_OR_DICT),
            Param::new("message", TY_ANY),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "websocket_server",
        params: &[
            Param::optional("bind", TY_STRING),
            Param::optional("options", TY_DICT),
        ],
        returns: TY_DICT,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
    BuiltinSignature {
        name: "websocket_server_close",
        params: &[Param::new("server", TY_STRING_OR_DICT)],
        returns: TY_BOOL,
        type_params: &[],
        has_rest: false,
        where_clauses: &[],
    },
];
